### ISSUE TITLE
Update the Dutch translation again

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1016]
I plan to cut a release in the next couple of days, and we have a few new strings since the last one, would love to have an updated Dutch translation.

@BrunoChevalier, can I ask you to update the strings, please?

On a side note, is there a better way to ping you than github issues? Email, Mastodon, the Keyboardio forums, Discord, anything? If there is, and you don't want to publicly share it, drop me a mail at algernon@keyboard.io, please. Thanks!

**Comment by BrunoChevalier** [comment]
Sent you a mail and added the missing translations
