### ISSUE TITLE
Buttons on the flashing instructions dialog should be clearer

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1023]
(Copied from https://github.com/keyboardio/Chrysalis/issues/989#issuecomment-1199643605)

> after i select a firmware version and click Update, if not holding Esc, i see a dialog box telling me to hold Esc before clicking Update, with options of Cancel and OK. it's not clear to me at this point whether i should
> 
> * click CANCEL, and then from the previous screen, hold Esc and click Update
> * hold Esc and click OK
> 
> i think i would prefer that dialog box to offer Update and Cancel buttons, provided it's possible to implement a flow of hold Esc, click Update in the dialog box, and then proceed with the firmware update process. if that's not possible, please offer only a Cancel button.

We should be updating the instructions to match the new flashing workflow for one, and we should also update the button labels to say "Cancel" and "Update", to make it clear what they do.

**Comment by obra** [comment]
I think we should stick with cancel instead of introducing “abort”
