### ISSUE TITLE
Shift+Key is showing as Ctrl+ (`C+?`) instead of `S+?`

### ISSUE THREAD

**Issue by mattmc3** [keyboardio/Chrysalis#1026]
**Describe the bug**
Shift+Key is showing as Ctrl+ (`C+?`) instead of `S+?` in Version 0.11.0.

**To Reproduce**
- Add a shortcut on a new layer with the SHIFT toggle, and C+ shows in the image instead of S+

**Expected behavior**
S+ indicates shift+

**Screenshots**
<img width="796" alt="Screen Shot 2022-07-30 at 9 12 06 AM" src="https://user-images.githubusercontent.com/978625/181916056-fdf675d1-7ba0-48f0-931c-5941c0ffd875.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Chrysalis Version: 0.11.0

**Additional context**
Debug bundle:
[chrysalis-debug.bundle.json.zip](https://github.com/keyboardio/Chrysalis/files/9226527/chrysalis-debug.bundle.json.zip)

**Comment by algernon** [comment]
My bad, the fix in 62f6ba5034abcd31d71d38ff9a4f2f40be39f433 wasn't good, and broke the default "English (US)" layout at least. I have a fix pending, it'll be in a snapshot soon.
