### ISSUE TITLE
Feature request: Always display a key's primary action in a large font (when space so permits)

### ISSUE THREAD

**Issue by parke** [keyboardio/Chrysalis#1033]
When a key has both a primary action and a secondary action, both actions are displayed in a small font.

This is the case even when there is plenty of space to display the primary action in the normal (i.e. large) font.

This is the case as of Chrisalis version 0.11.1-snapshot, and seems to have been the case since at least version 0.8.6 (and probably since earlier versions as well).

Here is a screenshot:

![20220822_atreus](https://user-images.githubusercontent.com/1454858/186057926-840a6c70-4a21-487c-ad5f-8278d76a4d22.jpg)

In the above screenshot, note that the selected key has a primary action of `E` and a secondary action of "shift to layer 4".

Note that the `E` on the selected key is displayed in a smaller font than the `O` on the key to the left of the `E`.

However, there is plenty of space on the key to display the `E` in the same size font as the `O`.  I think it would look better if primary actions were always displayed in the normal (i.e. large) font.  (Provided that there is sufficient space on the key for a large-font-primary-action, which there always would whenever the primary action is a single character, as in the screenshot above.)

**Comment by algernon** [comment]
Hmm. This *should* be easy to fix: we just need to modify the keymap SVGs to always render single-letter primary actions in a large font. That should work across the board.

It's certainly worth exploring if that is enough, and if it doesn't break anything (it shouldn't).
