### ISSUE TITLE
Wrong modifier displayed on key

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#1035]
**Describe the bug**

A key set with the 'shift' modifier is being displayed as 'ctrl' instead

**To Reproduce**

Set a key to press the `\` key with a Shift modifier.

**Expected behavior**

The brief display in the corner should show `Shift+\` and the keyboard overlay should show `S+\`

**Screenshots**

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/347162/186977889-2659bf46-35b2-4997-ae03-a8fc9d804f7f.png">

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/347162/186978140-796cd1a1-f049-447f-8ad7-50689cb6e05a.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Chrysalis Version: 0.11.0

**Additional context**
First time running Chrysalis in a while, and I'd been informed at startup that some legacy keys had to be migrated. I don't think that's relevant to this specific key though.

**Comment by algernon** [comment]
This should be fixed on master, can you try the latest snapshot package, please?

**Comment by fluffy-critter** [comment]
Ah, so it is, and it actually displays `|` which is even better.
