### ISSUE TITLE
Key Picker Ready To Use Without Resizing

### ISSUE THREAD

**Issue by TrueFalcon** [keyboardio/Chrysalis#1047]
Can we get the key picker to open BIG ??!!

![Chrysalis with Big Key Picker ](https://user-images.githubusercontent.com/7477419/190029018-77c0502f-973b-4fce-85d5-bc7d8955f647.jpg)

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this bit of UI has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
