### ISSUE TITLE
We need a test to verify that everything is included in packaged builds

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1052]
We just had a terrible accident, where it turned out that we weren't shipping `dfu-util` in production builds for a good while now, resulting in any and all Model100 flashes to fail, unless they were run from a git checkout.

We need a test that verifies that everything that needs to be bundled with Chrysalis, is bundled with it.

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
