### ISSUE TITLE
Flashing can fail without proper error reporting if the bootloader port lacks permissions

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1068]
If Chrysalis has permissions to write the serial port, but lacks permissions to open the bootloader for DFU, then flashing will fail, and we do not display a suitable error message, nor do we offer to install our udev rules (which would solve the issue).

We should be doing both.

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
