### ISSUE TITLE
Cannot connect to Atreus using Chrysalis

### ISSUE THREAD

**Issue by ksheng** [keyboardio/Chrysalis#1077]
**Describe the bug**
When using Chrysalis to connect to an Atreus keyboard, instead of displaying the keymap, a blank screen is displayed.

Errors in the development console are below:

![Screen Shot 2022-09-25 at 15 02 52 PM](https://user-images.githubusercontent.com/1018730/192168157-c9b41db6-f512-4871-b466-2e0179a69947.png)

**To Reproduce:**
* Open Chrysalis at version 0.11.3
* Plug in the Atreus
* Select it in the Chrysalis UI and click "Connect"

**Expected behavior:**
The keymap view is displayed when connecting.

**Desktop (please complete the following information):**
* OS: MacOS Monterey 12.6
* Chrysalis Version: 0.11.3

**Comment by obra** [comment]
Hi Kevin,

Is this the first time you're using Chrysalis with this Atreus or is this a
regression for you? Could you give 0.11.4 a shot to see if it behaves
better?

**Comment by ksheng** [comment]
Hey Jesse, this is a regression from a very old version. The Atreus had been working normally with (I believe) version 0.7.9 from July 2020.

I just tried with 0.11.4 and it was still the same behavior.

**Comment by obra** [comment]
Can you go into the Chrysalis prefs and turn on 'verbose logging':

![image](https://user-images.githubusercontent.com/45416/192387203-b699df44-0093-4a3b-b779-7d846c1399c0.png)

And then try the connection. When it fails, head over into the menu and pick "Report a problem" and download and attach the debugging bundle .json.txt file it generates?

**Comment by ksheng** [comment]
Ah, ran into a snag. I enabled verbose logging, but when I go to click "Connect", the entire window goes white (the buggy behavior) and there is no longer a "Report a problem" button.

Where does the app write to in the filesystem? I can try finding it from the command line.

**Comment by obra** [comment]
If you open up the developer console, (the radio button right next to
verbose logging), then you should get the bits we really need in the
console (which won't go white)

**Comment by ksheng** [comment]
That worked! Here's the downloaded log from the developer console:

[atreus.log](https://github.com/keyboardio/Chrysalis/files/9651356/atreus.log)

**Comment by bjarkevad** [comment]
I'm seeing that same issue with Chrysalis 0.11.5 on Linux (Arch Linux, using AppImage installed from here https://aur.archlinux.org/packages/chrysalis-bin) and two different Atreus keyboards. Connecting to a Model 100 works correctly.

**Comment by bjarkevad** [comment]
![image](https://user-images.githubusercontent.com/1748368/194777300-68ae6cdf-e2f6-472e-a275-faeeac1700b5.png)
I'm seeing this error with the latest snapshot. I've flashed a few simple macros on both keyboards back when I first got them, could that be causing problems? The "Report a problem" option is causing this build to freeze on my laptop, but I took this screenshot of the console 
![image](https://user-images.githubusercontent.com/1748368/194777472-1ee784fd-64b8-4064-a7f5-9fbe4de6ac7d.png)

**Comment by bjarkevad** [comment]
Chrysalis works after flashing stock Kaleidoscope!

**Comment by ksheng** [comment]
On the latest version (Chrysalis 0.12.0), I'm now getting this error instead of a blank screen when trying to connect. Here's the error message, and I've attached the [debug log](https://github.com/keyboardio/Chrysalis/files/9965293/atreus.log) from the developer console as well.

<img width="544" alt="Screen Shot 2022-11-08 at 13 07 52 PM" src="https://user-images.githubusercontent.com/1018730/200676358-2ca39147-ef3e-4be0-b16f-25593f7329a6.png">

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
