### ISSUE TITLE
replace "default layer" dropdown in the right hand corner with a checkbox on the layer's page

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#108]

**Comment by algernon** [comment]
Latest idea: use a [contextual action bar](https://material.io/design/components/app-bars-top.html#contextual-action-bar). This would pave the way for adding support for editing the layer names, too, on the same context.

**Comment by obra** [comment]
It's better than the menu on the tab, but I still worry that it's not
discoverable. I suppose we could have text and an changeable icon or
something.
