### ISSUE TITLE
autoupdate completion should offer to do the restart

### ISSUE THREAD

**Issue by tlyu** [keyboardio/Chrysalis#1081]
**Describe the bug**
Autoupdate says to restart to apply the change, but only has a button to dismiss the message. Manually quitting and restarting doesn't apply the update.

**To Reproduce**
Steps to reproduce the behavior (reconstructed from memory because I don't want to go through reinstalling an old version):
1. Start Chrysalis 0.11.3 with autoupdate enabled.
2. Start the update process when prompted.
3. Click the `X` button to dismiss the download completion message.
4. Press `Command-Q` (on macOS) to quit the application.
5. Restart Chrysalis.
6. Observe that Chrysalis begins another autoupdate cycle.
7. Realize that there might be a menu item to restart and apply update, and select it.
8. Update actually completes.

**Expected behavior**
Chrysalis should notice that it's been manually restarted after downloading an update, and apply the update.
Alternatively, Chrysalis should display a button to offer to do the restart, in addition to a button to dismiss the download completion message.
Either way, it should mention that there is a (temporarily available) menu item to apply the downloaded update.

**Screenshots**
N/A, because I don't want to replicate the upgrade process by downgrading at the moment.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2026)
 - Chrysalis Version: 0.11.3

**Additional context**
N/A

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality no longer exists, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
