### ISSUE TITLE
Let me easily return to the default keyboard

### ISSUE THREAD

**Issue by HMMcIntosh** [keyboardio/Chrysalis#1085]
**Is your feature request related to a problem? Please describe.**
Yes.  When I tried to change a key, I lost all the other keys (they now do nothing—only the key I changed works).  

**Describe the solution you'd like**
A clear and simple way to restore my keyboard to its default keys.

**Describe alternatives you've considered**
Throwing my Keyboardio out the window.

**Additional context**
I expected a keyboard as good as the Keyboardio would come with software that was equally as good.  It didn't.  Chrysalis is *terrible*.  If I gave you a list of the frustration in my 30 minutes trying to do something simple with this software I'd be here all morning.  Now I'm left with a keyboard that doesn't work.

I'm not even sure Chrysalis is worth fixing.  If I were you, I'd get a new software developer and have them start from scratch.

**Comment by tlyu** [comment]
Have you tried the steps in https://community.keyboard.io/t/model100-back-to-factory-layout/5568 ?
