### ISSUE TITLE
increase font size in key labels

### ISSUE THREAD

**Issue by tlyu** [keyboardio/Chrysalis#1094]
**Describe the bug**
In the Layout & Colormap Editor, key labels are small enough to be nearly illegible to me, maybe especially on a Retina (or maybe other HiDPI) display.

**To Reproduce**
1. Go to 'Layout & Colormap Editor'.
2. Try to read the key labels on the keyboard preview.

**Expected behavior**
Key labels should be more legible. Changing to `font-size: 10px` on both `.layer` and `.extra-key` by editing the CSS in Developer Tools seems to result in a good balance of increasing readability and avoiding overflowing the key outlines. A lot of emoji key labels are still difficult for me to read at this size, so maybe there needs to be an even larger size used for emoji key labels.

**Screenshots**
N/A; probably need to view on an actual screen to see.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2026)
 - Chrysalis Version: 0.11.4

**Additional context**
N/A

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this UI has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
