### ISSUE TITLE
Chrysalis loses connection to keyboard but doesn't notify / update the UI

### ISSUE THREAD

**Issue by aconbere** [keyboardio/Chrysalis#1107]
**Describe the bug**
When running Chrysalis for longer periods of time in the background, when returning to the application the UI appears to be in a good state, however subsequent actions fail to render correctly (at least once the result was just a plain white page). Refreshing the page (Cmd-r) returns to the "select keyboard" page and everything works fine after that. Closing and quitting the app also restores functionality.

**To Reproduce**
1. Open Chrysalis and connect it to a keyboard
2. Wait a while (Order of hours)
3. Try doing something like viewing the layout card
4. OH NO!

**Expected behavior**
I think in an ideal case if Chrysalis is aware of the lost connection that it would either pop up a modal letting me know what's happened or just returned me to the "select keyboard" screen already.

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Chrysalis Version: 0.11.4 (0.11.4)

**Comment by aconbere** [comment]
<img width="1563" alt="Screen Shot 2022-09-29 at 8 44 01 AM" src="https://user-images.githubusercontent.com/17713/193077875-2ccbd7b9-cffb-4bc6-b72f-2172459a2412.png">
<img width="569" alt="Screen Shot 2022-09-29 at 8 44 48 AM" src="https://user-images.githubusercontent.com/17713/193077884-47ec897b-7256-49fb-b187-ce0dd9858ef7.png">

**Comment by aconbere** [comment]
[chrysalis-debug.json.txt](https://github.com/keyboardio/Chrysalis/files/9676272/chrysalis-debug.json.txt)

**Comment by algernon** [comment]
From the logs, it looks like we are, indeed, reporting the disconnect properly, so I suspect that the re-render might be responsible for the errors, and by way of the uncaught exception, for not finishing the handler properly.

**Comment by algernon** [comment]
Ok, quick experiment shows that at least on Linux, we do fire an event when the keyboard disconnects. But it never does anything, we never get past these checks:

```
    if (!focus.focusDeviceDescriptor) return;
    if (flashing) return;

    if (
      focus.focusDeviceDescriptor.usb.vendorId != vid ||
      focus.focusDeviceDescriptor.usb.productId != pid
    ) {
      return;
    }
```

I assume the same thing happens on other platforms. Which means we're not handling disconnects properly. Anything else that runs after the `handleDeviceDisconnect` is thus running with false assumptions.

**Comment by algernon** [comment]
for some odd reason, `focus.focusDeviceDescriptor` is null there. I don't yet know why.

**Comment by algernon** [comment]
Hrm. `focus.close()` nulls that out, so now I have to figure out where that is called from, and we should be good.

**Comment by algernon** [comment]
Oooh! We have an `on("close")` handler on the port in `api/focus`, which does call `focus.close()`.
