### ISSUE TITLE
Factory Reset is a lie when connecting in bootloader mode

### ISSUE THREAD

**Issue by tlyu** [keyboardio/Chrysalis#1112]
**Describe the bug**
One workaround for poor communications with Chrysalis and the factory Model 100 firmware is to force bootloader mode before connecting in Chrysalis. Unfortunately, if you then select the Factory Reset option when prompted to upgrade the firmware, the EEPROM does not get erased, despite the UI feedback implying that it will.

**To Reproduce**
1. Start Chrysalis without the keyboard connected.
2. Plug in a Model 100 keyboard while holding down PROG, to force bootloader mode.
3. Connect to the keyboard in Chrysalis.
4. Click Upgrade Firmware when prompted.
5. Select Factory Reset, and click the prompts to continue.
6. Observe that flashing completes, but only performs a "flashing" step.
7. Reconnect to the keyboard in Chrysalis.
8. Observe that any previous custom keymap layout settings remain intact.

**Expected behavior**
"Factory Reset" should behave as advertised, even when using the "connect to Chrysalis while in bootloader mode" workaround for poor connectivity with factory firmware.

**Screenshots**
N/A; there are lots of steps involved, and the description is hopefully clear enough to replicate the failure.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2026)
 - Chrysalis Version: 0.11.5, but also 0.11.4 and maybe earlier as well.
 
**Additional context**
I came across this while trying to provide more robust steps for reflashing from Model 100 factory firmware in #1108.

**Comment by algernon** [comment]
I had an attempt at this, but it's Difficult™, for a number of reasons. The major one being that `Model100` and `Model100Bootloader` are separate things, so if we're in bootloader mode, reconnecting to a normal mode keyboard does not currently work. This is one of the issues highlighted in #1015.

We also have a couple of other stability problems. It's hard to describe them, because it's complicated and messy, so I'd like to discuss it on Discord instead.

**Comment by algernon** [comment]
As an interim solution, I'd remove the factory reset switch if the keyboard is in bootloader mode, to not set false expectations.

**Comment by algernon** [comment]
...but doing that temporary removal isn't trivial either, for similar reasons. *sigh*
