### ISSUE TITLE
Secondary Action Modifiers deficiencies

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Chrysalis#1117]
**Describe the bug**
When defining a Secondary Action Modifier, the corresponding item in the Modifiers section shows as being selected.  This could be interpreted as that modifier applying to the primary `Key`, though it does not.

In addition, Chrysalis limits the modifiers selectable to only the five that can be added to the base keycode in the Modifiers section, rather than allowing the user to select any of the eight available in the DualUse `Key` definition.

**To Reproduce**
1. Select a Keyboard key (e.g. `X`)
2. Expand both the Modifiers and Secondary Actions sections
3. Set "When held" to "Modifier", and "Modifier" to "Control"

Note that, although the controls in the Modifiers section above Secondary Actions is disabled, it shows "Control" as enabled.  This is incorrect, and possibly misleading.

Also note that the only options in the "Modifiers" list under "Secondary Actions" and the five modifiers that can be added to Keyboard keys with modifier flags, whereas DualUse keys can produce any of the eight keyboard modifiers.

**Expected behavior**
The list should probably look like this, instead:

"Left Control"
"Left Shift"
"Left Alt"
"Left Command/GUI/Win" (depending on OS, of course)
"Right Control"
"Right Shift"
"Right Alt (AltGr)"
"Right Command/GUI/Win"

…and selecting one of these should disable the Modifiers section, but show all of the options there as turned off.

**Screenshot**
<img width="340" alt="Screen Shot 2022-09-29 at 1 21 21 PM" src="https://user-images.githubusercontent.com/17190757/193112255-07c88ac3-dce0-4c96-9b46-d3ad90254f51.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrysalis Version: 0.11.4

**Comment by algernon** [comment]
I can easily fix the main part, the "Modifiers" section showing the modifier as on when it's DualUse. Adding the rest of the modifiers to the dropdown is slightly trickier, but I'll see what I can do.
