### ISSUE TITLE
Chrysalis will not save to my Model 01

### ISSUE THREAD

**Issue by sixears** [keyboardio/Chrysalis#1119]
Chrysalis 0.11.5 never un-greys the "download" button to allow me to save changes to my Model01

**To Reproduce**
1. Go to Layout & Colormap Editor
2. Make a change to a key
3. Bounce like a crazed gibbon on the save/download button in the bottom-left corner.  It is a pleasing but futile light grey colour.

**Expected behavior**
Once I had changed a key, I would expect the download/save button to un-grey.

**Desktop (please complete the following information):**
 - OS: nixOS 22.05
 - Chrysalis Version: 0.11.5

**Comment by sixears** [comment]
btw, Chrysalis prompted me to updated firmware; which I did successfully.
The firmware is now 0.90.2+44 .
It wouldn't let me save before I updated; reasoning that I needed to update fw to save, I went ahead.  I'm afraid I didn't note which firmware I was previously using.

**Comment by obra** [comment]
Now that you've updated, is it working ok?

**Comment by algernon** [comment]
Oooh. I think I know the problem. It would be the `layerNames` bounds check. It's probably failing on keyboards that do not have the `LayerNames` plugin enabled, such as the Model 01. I'll post a PR fixing it in a moment.

**Comment by mattmc3** [comment]
I can confirm - I have the same issue on my Model 01.

**Comment by sixears** [comment]
> Now that you've updated, is it working ok?

No, the update had no effect. I had made the update before I posted the issue; I was back-filling the info. about having tried the fw, to no avail.

Sorry, I realize I could've made that much clearer.

**Comment by sixears** [comment]
I can confirm that the fix, as of 0.11.6-snapshot.141, is working for me.  Thank you.
