### ISSUE TITLE
Sometimes the flashing process fails to properly enter bootloader mode on the Model 100

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1154]
As the title says. I have noticed that sometimes my keyboard fails to enter bootloader mode, despite properly holding the PROG key, and the keyboard functioning fine otherwise. Not sure yet if it's a problem in Chrysalis or elsewhere, but it needs investigating.

**Comment by Moilleadoir** [comment]
It seems to have stopped working entirely for me with 0.11.7.

**Comment by obreitwi** [comment]
Encountered the same problem: No flashing of model 100 possible in 0.11.7 by holding down `PROG` during flashing.

Workaround: Holding `PROG` while connecting the model 100 (just like the [initial flash](https://community.keyboard.io/t/model-100-firmware-update-to-fix-corruption-issues/5553)) still works.

**Comment by clemensw** [comment]
I also can't flash the M-01 or the Atreus with 0.11.7.  I always get the message that the Keyboard has not entered programmable mode. On the M-01 there are also no LEDs activated while holding PROG when pressing 'continue'
