### ISSUE TITLE
Collapsing sections on the Editor Sidebar

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1159]
Most of the sections on the Editor Sidebar are collapsible, but the behaviour of these sections can maybe be surprising. They all have three states: "automatic", "expanded", "collapsed". By default, every section is in the automatic state, which means they expand or collapse based on what key is currently selected. Once someone manually changes the state, either to expand or collapse a section, it will no longer automatically change state.

The idea behind this behaviour was that showing unnecessary sections is not desirable, the sidebar would get far too high with everything expanded all the time. However, this behaviour might be surprising, and unintuitive.

How could we do better?

**Comment by EvyBongers** [comment]
When just connecting a keyboard and first selecting a key, I would expect either of these:
- have/leave everything closed
- open those sections where options are enabled for the selected key

When selecting a different key, I would expect sections to stay in whatever state they are.
