### ISSUE TITLE
ci: Update the Actions we use

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1169]
Some of the Actions we use appear to be slightly outdated, to the point of GitHub warning about them:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-node, actions/cache, samuelmeuli/action-electron-builder, actions/upload-artifact, actions/cache

Some of these probably have newer versions that use Node16, and we should migrate off the ones that don't by summer 2023, I suppose.

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB, so I'm closing out this issue as obsolete.
