### ISSUE TITLE
Rebooting to bootloader mode during flashing is fragile

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1178]
First reported [on the forums](https://community.keyboard.io/t/chrysalis-0-11-8-firmware-flashing-is-unreliable/5744?u=algernon), and I reproduced locally.

The symptom is that flashing a Model100 (not sure yet if other keyboards are affected), rebooting to bootloader mode just doesn't work, even though `Prog` is correctly pressed, and there are no other software interfering. During reproduction, I discovered that if I do **not** hold `Prog` during the first reboot, but start holding it anytime after, then all goes well, and the flash succeeds. If I hold `Prog` during the first attempt, then it will never work again, unless I unplug & replug with Prog held.

I have no idea what causes this yet, but this needs to be fixed ASAP.

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
