### ISSUE TITLE
Use WebDFU for flashing Model100s

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1186]
We are currently using `dfu-util` (which we ship alongside Chrysalis ourselves) to flash the Keyboardio Model100. It's... not great. First of all, it is an external tool over which we have little control, so we're forced to work around its quirks. Second, we're using different builds of it for our three different platforms, all of which have their own quirks.

Ideally, we would want something cross-platform, with less quirks, where we have more control over the process. WebDFU feels like the best way to accomplish that.

**Comment by obra** [comment]
This is done
