### ISSUE TITLE
Dark splashscreen

### ISSUE THREAD

**Issue by Kilomil** [keyboardio/Chrysalis#1196]
**Is your feature request related to a problem? Please describe.**
The problem is that my eyes hurt when I open Crystalis in the evenings due to bright white splashscreen.

**Describe the solution you'd like**
For the background splash screen on windows to be the grey color from the dark theme. Or be the same color of the current theme if possible to know that before the splash screen displays. Alternatively to not show the splash screen at all, and just show the application when it is ready.

**Describe alternatives you've considered**
Alternatively to not show the splash screen at all, and just show the application when it is ready.

**Additional context**
![image](https://user-images.githubusercontent.com/1193250/197361788-9125f4ef-5fad-4357-beba-40264539f2d4.png)

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this feature has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
