### ISSUE TITLE
Restoring from backups is broken

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1201]
d4c3e1cd74ab62f5d137af3c87004a4e9db03684 changed the format of the backups. We can restore them during flash, because that uses the same, unparsed format anyway. However, the importing in "Backup & restore" expects a parsed format from the json, and the backups are no longer suitable.

As such, this part of the functionality is broken since 0.11.9.

That's not necessarily bad, because importing from backups wasn't really doing what people expected it to do to begin with: it only imported keymaps, colormaps, and the palette, and nothing else. I am working on making import / export work properly, so rather than backing the aforementioned commit out, I'd suggest either leaving it broken for now, or disabling importing from backups for the time being.

**Comment by obra** [comment]
The broken restore feature should really not be available to users.

**Comment by obra** [comment]
Backup and restore has been rewritten since this bug was an issue
