### ISSUE TITLE
can't dismiss onlyCustom=false screen

### ISSUE THREAD

**Issue by tlyu** [keyboardio/Chrysalis#1217]
## Describe the bug

When connecting to a keyboard that has `keymap.onlyCustom 0`, but isn't freshly erased, it's difficult to continue past the mixed-layout warning screen.

## To Reproduce

- Set `keymap.onlyCustom 0` on a Model 100 that has a non-blank EEPROM keymap
- Connect to the keyboard in Chrysalis
- Observe the warning screen
- Click the "switch to custom layers only" button
- Observe that the button activates, but nothing seems to happen

## Expected behavior

Chrysalis should proceed to the layout editor once it has successfully set `keymap.onlyCustom 1`.

## Screenshots

[chrysalis-debug.json.txt](https://github.com/keyboardio/Chrysalis/files/9892284/chrysalis-debug.json.txt)

## Desktop

 - OS: macOS 10.15.7 (19H2026)
 - Chrysalis Version: 0.12.0

## Additional context

Quitting Chrysalis after clicking the "switch to custom layers only" button and then checking `keymap.onlyCustom` via other means shows that it has changed the setting on the keyboard.

The following seems to work around the problem, but is not great:

- Go to the hamburger menu and selecting "Select another keyboard"
- Disconnect and reconnect

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been removed, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
