### ISSUE TITLE
layer resets upon releasing only one held ShiftTo key

### ISSUE THREAD

**Issue by mrwonko** [keyboardio/Chrysalis#1237]
**Describe the bug**
When you hold two keys that shift to the same layer (such as the two big "fun" buttons), releasing only one of them resets the layer.

**To Reproduce**
1. Hold both fun keys
2. Release one
3. Attempt to use a key from the shifted layer
4. The base layer key is used instead

**Expected behavior**
The layer-shift should only end when no more ShiftTo keys are held.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Chrysalis Version: 0.12.0

**Comment by obra** [comment]
Since this is a Kaleidoscope issue and not a Chrysalis one, I'm closing it in favor of https://github.com/keyboardio/Kaleidoscope/issues/1438
