### ISSUE TITLE
Unable to restore keymap from json export

### ISSUE THREAD

**Issue by shoan** [keyboardio/Chrysalis#1244]
**Description**
I had exported my atreus keymap with an earlier version of Chrysalis. Recently, I factory reset the atreus and was unable to restore the old keymap from the json file. After selecting the file, the preview does not show the expected changes to the base layer.

Interestingly, a much older keymap file received from someone on the internet, showed the expected changes in the preview.   

**To Reproduce**
1. Go to 'Backup & Restore'
2. Click on 'Load from file'
3. Select the attached broken.json
4. Observe that the keymap in the preview is not updated

**Expected behavior**
The keymap should have been updated

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also include the debug bundle you can create on the "Report a problem" screen. If, for some reason, you are unable to access that screen, please press `Control + Shift + I` (Windows or Linux) or `Command + Option + I` (macOS) to bring up the developer console. Right-clicking inside it will allow you to save its contents to a file - please attach that to the bug report.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrysalis Version: 0.12.0

**Additional context**
Also attached is a layout backup file (atreus-new-working.json) created with Chrysalis 0.12.0. This file can also be restored as expected. 
[atreus_broken.json.txt](https://github.com/keyboardio/Chrysalis/files/10298792/atreus_broken.json.txt)
[atreus-working.json.txt](https://github.com/keyboardio/Chrysalis/files/10298793/atreus-working.json.txt)
[chrysalis-debug.bundle.json.txt](https://github.com/keyboardio/Chrysalis/files/10298796/chrysalis-debug.bundle.json.txt)
[atreus-new-working.json.txt](https://github.com/keyboardio/Chrysalis/files/10298799/atreus-new-working.json.txt)

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this feature has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
