### ISSUE TITLE
Chrysalis Does Not Save Layer #0

### ISSUE THREAD

**Issue by gavinhoward** [keyboardio/Chrysalis#1256]
**Describe the bug**
I used Chrysalis to create [this `Layout.json`][1]. As you can see, Layer 0 is a modified Dvorak.

Nevertheless, after saving the configuration, the keyboard still acts like it has Qwerty as Layer 0.

**To Reproduce**
1. Download the latest Chrysalis release AppImage.
2. Make it executable.
3. Run it.
4. Import [this `Layout.json`][1].
5. Save the configuration.
6. Check for Qwerty

**Expected behavior**

I expected Dvorak.

**Screenshots**

I wasn't able to save a bundle. Chrysalis froze when I tried.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux, up-to-date
 - Chrysalis Version: 0.12.0

**Additional context**

I flashed the latest firmware before saving the configuration.

The other layers seem to work fine.

[1]: https://gavinhoward.com/uploads/Layout.json

**Comment by obra** [comment]
If you exit Chrysalis and restart, what does it show for Layer 0? If you go
into the keyboard settings, what do you see for the 'default layer' setting?

**Comment by gavinhoward** [comment]
It shows Dvorak, and the default layer is Layer 0.

Another weird thing is that Layer 1, which is supposed to be my Qwerty layer, switched to showing Dvorak.

**Comment by obra** [comment]
Do you have a second computer you can plug the keyboard into? I'd really
like to get a debugging bundle and also to see if the QWERTY behavior is
replicated on other devices.

**Comment by gavinhoward** [comment]
I do!

It is an Ubuntu 20.04 laptop.

The bundle is [chrysalis-debug.zip](https://github.com/keyboardio/Chrysalis/files/10737693/chrysalis-debug.zip).

When I compared the two computers, something interesting happened. The six images below are the keymaps on the Gentoo machine.

![Screenshot_2023-02-14_16-04-23](https://user-images.githubusercontent.com/3172687/218885528-a9b98d7a-2fa9-46c3-a39b-446657bb896f.jpg)
![Screenshot_2023-02-14_16-04-36](https://user-images.githubusercontent.com/3172687/218885551-55425af3-d96d-4cfa-b4c9-7722e0fb3826.jpg)
![Screenshot_2023-02-14_16-04-52](https://user-images.githubusercontent.com/3172687/218885565-6eec1481-88fa-4d4d-9834-f3af6c7a6413.jpg)
![Screenshot_2023-02-14_16-05-14](https://user-images.githubusercontent.com/3172687/218885592-508d1ee9-bbb0-4c43-9ff6-8d2a660b9545.jpg)
![Screenshot_2023-02-14_16-05-27](https://user-images.githubusercontent.com/3172687/218885605-a51cce33-132f-4578-8149-4afffdfba4e9.jpg)
![Screenshot_2023-02-14_16-05-43](https://user-images.githubusercontent.com/3172687/218885624-57b51f6d-b25b-4050-943b-96df056fc2c4.jpg)

(Adding an extra paragraph for space between screenshot sets...)

The six below were taken on the Ubuntu machine.

![Screenshot from 2023-02-14 15-57-46](https://user-images.githubusercontent.com/3172687/218885781-cee86720-48c8-4e1e-a35b-82d931a146ed.png)
![Screenshot from 2023-02-14 15-57-52](https://user-images.githubusercontent.com/3172687/218885807-73c33f6a-0d1e-4a96-8d3f-ff5bfc6be645.png)
![Screenshot from 2023-02-14 15-58-04](https://user-images.githubusercontent.com/3172687/218885814-30de451b-92fe-4b3e-b62c-abc3c305392e.png)
![Screenshot from 2023-02-14 15-58-08](https://user-images.githubusercontent.com/3172687/218885831-092fa4af-6823-4652-b44f-b9f6ae519738.png)
![Screenshot from 2023-02-14 15-58-11](https://user-images.githubusercontent.com/3172687/218885847-c4432057-17e2-419d-a15e-3d05b5528ee7.png)
![Screenshot from 2023-02-14 15-58-13](https://user-images.githubusercontent.com/3172687/218885856-e5bb22c6-e1fe-470c-b90b-314a3e173cd8.png)

I don't know why they disagree, but the one on the Ubuntu machine matches how the keyboard actually acts, I think.

I don't know what I'm doing wrong, but maybe I can import my JSON layout on the Ubuntu machine and make it work that way until the problem is debugged.

**Comment by gavinhoward** [comment]
By the way, both sets of screenshots were taken right after plugging in the keyboard and opening Chrysalis.

**Comment by obra** [comment]
Is the Chrysalis build you're using on Gentoo downloaded from our Github or
from their build?

**Comment by obra** [comment]
Oh. In the settings panel in Chrysalis, what have you set the host keymap
to on each OS?

**Comment by gavinhoward** [comment]
The build on both is downloaded from GitHub.

The keymap was different. I was stupid and didn't realize that that was supposed to be the keymap on the computer. PEBKAC as usual. I'm going to redo my layouts with it set the way it's set on the Ubuntu machine. If it works, I'll close this.

**Comment by gavinhoward** [comment]
As I thought, it was PEBKAC. I apologize.
