### ISSUE TITLE
Chrysalis window too small and has no move/resize controls

### ISSUE THREAD

**Issue by stevep99** [keyboardio/Chrysalis#1261]
**Describe the bug**
Upon launching, the app window is small, and can't be moved or resized. 
The issue occurs on my Fedora laptop, but not on my desktop machine (which has Pop! OS).

**To Reproduce**
1. Launch the AppImage.
2. Observe the Chrysalis app window.

**Expected behavior**
The app window should be large enough to see  the current keyboard and the key selection panel. It should also be resizable and moveable as per usual window controls.

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Chrysalis Version: 0.12.0  (plus several earlier versions)

**Additional context**
![Screenshot from 2023-03-13 16-25-05](https://user-images.githubusercontent.com/1632773/224766323-b468b558-b606-4f77-84fc-20ec692e3b6d.png)

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
