### ISSUE TITLE
Error while flashing firmware update - Uncaught (in promise) Error: Error: No such device, cannot open /dev/ttyACM0 Promise.then (async)

### ISSUE THREAD

**Issue by elpddev** [keyboardio/Chrysalis#1274]
**Describe the bug**
Trying several times to flash the latest firmware update for Atreus (0.91.1). Getting stuck on the second stage of the flashing process each time.

1. During the flashing, the internet get disconnected, each time. 
2. Every time, I have to restart the computer. Taking the keyboard out and in again does not help, only restart.

First error:

```
Uncaught (in promise) Error: Error: No such device, cannot open /dev/ttyACM0
Promise.then (async)
```

**To Reproduce**
1. Open dev console
3. Go to fireware update
4. Click update
5. Press lower left button and continue pressing
6. Click confirm on dialog to continue flashing

**Expected behavior**
Flash operation end succesfully.

**Screenshots**
![Pasted image 20230531080016](https://github.com/keyboardio/Chrysalis/assets/17731302/ef442242-fe18-4a7d-b330-c5e0a871004a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Chrysalis Version: Chrysalis 0.13.3-snapshot

**Additional context**

```
ll /dev/ttyACM0
crw-rw----+ 1 root dialout 166, 0 May 31 08:24 /dev/ttyACM0
```

```
groups myuser
myuser : myuser adm dialout cdrom sudo dip plugdev lpadmin lxd sambashare
```

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
