### ISSUE TITLE
"Error flashing the firmware" Keyboardio Atreus at Archlinux

### ISSUE THREAD

**Issue by artkpv** [keyboardio/Chrysalis#1275]
**Describe the bug**
Chrysalis 0.13.2 can't finish flashing the firmware 0.91.1 on my Keyboardio Atreus.

**To Reproduce**

1. `sudo chmod 666 /dev/ttyACM0`
2. Enter the page to flash
3. Press Flash
4. Hold ESC and start the flashing

Result:
The progress bar goes till 'Flashing' point and I'm kicked off to the Select keyboard screen.

**Expected behavior**

Flashing the keyboard finishes.

**Screenshots**

![screenshot_1685772428](https://github.com/keyboardio/Chrysalis/assets/3657998/41289d24-b820-4c05-9367-ff04f2826833)
![screenshot_1685772436](https://github.com/keyboardio/Chrysalis/assets/3657998/019083ef-0f2f-4ad1-9592-988ce48b4e65)
![screenshot_1685772452](https://github.com/keyboardio/Chrysalis/assets/3657998/d4ad831d-33a8-47e0-8a42-394a8f473b6b)
![screenshot_1685772459](https://github.com/keyboardio/Chrysalis/assets/3657998/32533ac2-146f-4bf6-bf49-5a7b8ad96512)
![screenshot_1685772465](https://github.com/keyboardio/Chrysalis/assets/3657998/9c9d3561-b33a-43eb-9f52-600d1a32a6b3)

**Desktop (please complete the following information):**
 - OS: 

```
> uname -a
Linux ARCHPC 6.3.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 24 May 2023 17:44:00 +0000 x86_64 GNU/Linux
``` 

- Chrysalis Version: Chrysalis 0.13.2

**Additional context**
Also, recently I got issue #1272 but cleaning up the connection hole helped.

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
