### ISSUE TITLE
A few issues with printing the Layout Card

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#1281]
**Describe the bug**

In some cases, printing the Layout Card will include scroll bars on the right side. In those cases, it is also very likely that the last page will have a cropped layer printed, too.

**Screenshots**

See the attached PDF for an example, generated from my own Model 100 layout.

**Desktop (please complete the following information):**

- OS: Debian
- Chrysalis Version: 0.13.2, and current git head too. Possibly earlier versions aswell.

[output.pdf](https://github.com/keyboardio/Chrysalis/files/11786263/output.pdf)

**Comment by wwkeyboard** [comment]
This happens on macos as well, I'm attaching a sample generated from an atreus layout. Also with 0.13.2


[Chrysalis.pdf](https://github.com/keyboardio/Chrysalis/files/11952433/Chrysalis.pdf)

**Comment by edysli** [comment]
Chrysalis' menu bar also appears in the printed layout. [This sample](https://github.com/keyboardio/Chrysalis/files/12024163/model100_layout.pdf) happened on Ubuntu 22.04 with Chrysalis 0.13.2.

**Comment by detzt** [comment]
I have the same issue on windows as well.

**Comment by obra** [comment]
I believe the layout card should now print correctly
