### ISSUE TITLE
Nested modifiers are incorrectly visualized

### ISSUE THREAD

**Issue by hupfdule** [keyboardio/Chrysalis#1288]
**Describe the bug**
I have a key defined in the .ino file as `LSHIFT(RALT(Key_RightControl))`.
In Chrysalis this is displayed like this:
![image](https://github.com/keyboardio/Chrysalis/assets/36069345/ea2cefe9-f10b-49d7-95d3-d4a43685d7e1)

In they keyboard visualization (1) it is correctly displayed as `S+AGr+Ctrl`.

In the reference keyboard (2) the right Ctrl is correctly selected.

But in the “Modifiers” section (3) the Shift and AltGr keys are not selected.

**To Reproduce**
1. Add such a key in the .ino file
2. Build the firmware
3. Install the firmware
4. Open Chrysalis
5. Select the key

**Expected behavior**
The Shift and AltGr keys should be seleted in the ”Modifiers” section.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrysalis Version: 0.13.2

**Comment by obra** [comment]
I believe this to have been resolved in current chrysalis.
