### ISSUE TITLE
Problem with keys associated with Dynamic Macros

### ISSUE THREAD

**Issue by fipar** [keyboardio/Chrysalis#1289]
**Describe the bug**
When using 0.13.2 with a model 100, I only see Dynamic Macros starting at 10, and the description for keys associated with DMs mention Topsy Turvy instead of the DM number as before. 

I am running firmware 0.91.1+74

**To Reproduce**
 - Open the Layout & Colormap Editor on 0.13.2 (though I suspect this may happen on any version since support for Topsy Turvy was added) and a model 100 with some keys bound to DMs (I am including a screenshot of how this looks to me, along with one of how this looks on 0.11.18

**Expected behavior**
I can view and edit all DMs as before, and key descriptions are DM # <macro number> for keys bound to DMs.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1 (a)
 - Chrysalis Version: 0.13.2

**Screenshots**
![image](https://github.com/keyboardio/Chrysalis/assets/87147094/3ee97cce-d772-4048-8fe3-f082b936acb3)
![image](https://github.com/keyboardio/Chrysalis/assets/87147094/274f70a9-f88f-4bdf-9d79-ebfc2ae1a38c)

**Additional context**
I was able to get my original behavior back by installing 0.12.0

**Comment by obra** [comment]
I believe this to be fixed on https://chrysalis.keyboard.io
