### ISSUE TITLE
Layout Editor doesn't indicate in the key label when Shift modifier is added for letters.

### ISSUE THREAD

**Issue by NabiYang** [keyboardio/Chrysalis#1302]
**Describe the bug**
Using the Shift toggle to add shift to a key that types a letter doesn't show any indication in the key label. For example, if the letter A is assigned to a key, adding Control causes the label to read, "C+A". If I add the shift modifier to punctuation such as [, then it will show the shifted version {. But all the letters are shown in caps already in the layout editor, even though they aren't shifted. So it's impossible to tell from the label whether shift is included with that key without something like "S+A".

**To Reproduce**
1. Open Chrysalis and connect to keyboard.
2. Select a key that has a letter assigned to it.
3. Toggle on Shift under Modifiers.
4. The label remains the same.

**Expected behavior**
I expect the label to change indicating that shift is added to the letter.

**Screenshots**
<img width="980" alt="Unmodified A" src="https://github.com/keyboardio/chrysalis/assets/58035835/1f2ff5b5-32ed-4313-88c2-4daca28e00c4">
<img width="980" alt="Shifted A - This is the bug" src="https://github.com/keyboardio/chrysalis/assets/58035835/fd564a4d-b91c-4659-b70d-07ba53dceb8f">
<img width="980" alt="Control A - For comparison" src="https://github.com/keyboardio/chrysalis/assets/58035835/894f6200-99ad-4e3b-8959-184581c456af">
[-1692650178604.log](https://github.com/keyboardio/chrysalis/files/12402335/-1692650178604.log)

If applicable, add screenshots to help explain your problem. If possible, please also include the debug bundle you can create on the "Report a problem" screen. If, for some reason, you are unable to access that screen, please press `Control + Shift + I` (Windows or Linux) or `Command + Option + I` (macOS) to bring up the developer console. Right-clicking inside it will allow you to save its contents to a file - please attach that to the bug report.

**Desktop (please complete the following information):**
 - OS: Windows 11 version 10.0.22621 Build 22621
 - Chrysalis Version: 0.13.2

**Additional context**

**Comment by obra** [comment]
I believe this to be fixed on https://chrysalis.keyboard.io. Please let me know if it isn't
