### ISSUE TITLE
Check firmware update yields version [object Object]

### ISSUE THREAD

**Issue by Kilomil** [keyboardio/Chrysalis#1311]
**Describe the bug**
Trying to get new chrystalis firmware version for model 100 was very slow and at the end the new version it got from the check was [object Object]

**To Reproduce**
1. I installed the new Chrystalis on top of my old installation.
2. I went to menu Firmware Update
3. wait a while
4. it reports newest version is [object Object]

**Expected behavior**
That I would get a proper version. Or if fetching the version fails, that it would not show me to update to an unspecified version and maybe an error popup.

**Screenshots**
![image](https://github.com/keyboardio/Chrysalis/assets/1193250/06b175f8-4d06-411c-ad69-a2f2488831f6)
![image](https://github.com/keyboardio/Chrysalis/assets/1193250/cdcee6cf-219b-4853-9e4f-47fe671ea740)

[chrysalis-debug.json.txt](https://github.com/keyboardio/Chrysalis/files/12774225/chrysalis-debug.json.txt)

**Desktop (please complete the following information):**
 - OS: win 10
 - Chrysalis Version: [e.g. 0.13.2]

**Additional context**

**Comment by obra** [comment]
it does look like you have the most recently released version of the
firmware. (We briefly released in 0.92 and then pulled it after hearing
reports of a possible issue from one customer.)

if this is reproducible, is there anything in the developer console error
log?

**Comment by Kilomil** [comment]
Is the snapshot 2 I provided not the developer console error log?
And yes its reproducible. Just tried, same result and the console output is the same as provided in snapshot 2.
I see someone in the discord channel showing a snapshot for them, and I can see they, on their model 100, have firmware version 0.91.0+74, where I only have 0.91.0+68.
https://media.discordapp.net/attachments/492409398493446146/1157642118785925150/image.png?ex=651aab3d&is=651959bd&hm=ea3a71fdc43b7b2e25da6bfa1f37ca02cc99db6d251f4aee823976da4efe8c1d&=&width=858&height=608

**Comment by Kilomil** [comment]
I also just tried to uninstall both v12 and 13 of chrystalis, and then re-install v13. Same result.

**Comment by obra** [comment]
Indeed it was. So sorry. I'm not sure why it didn't render for me the first
time I looked.

That "file not found" error does kind of hint that something might be
wrong. Can you grab a snapshot of the network panel to see if it can show
off what's not getting loaded?

**Comment by Kilomil** [comment]
![image](https://github.com/keyboardio/Chrysalis/assets/1193250/c90f1053-1fe2-4a20-b737-94902b774643)
I dont see much activity in the network log

**Comment by Kilomil** [comment]
![image](https://github.com/keyboardio/Chrysalis/assets/1193250/67b26fbe-f940-401e-8e0c-ce92aa0701e0)
![image](https://github.com/keyboardio/Chrysalis/assets/1193250/e5b62e30-8f72-4a1c-8dcd-fcd9a1d657d7)
Managed to capture a few more

**Comment by obra** [comment]
Chrysalis now runs in-browser using WebSerial and WebUSB, so I'm closing out this issue as obsolete.
