### ISSUE TITLE
db.js dual-use modifiers section doesn't match dualuse.js after right hand modifiers were added.

### ISSUE THREAD

**Issue by NabiYang** [keyboardio/Chrysalis#1316]
**Describe the bug**
Right hand modifiers with indices 4, 5, and 7 were added to dualuse.js but they're absent from db.js in the setLayout(). The dual use right hand modifiers work correctly when assigned in Chrysalis, so I'm unsure what difference this makes. But it's worth looking at.

**To Reproduce**
1. Check the "// dual-use modifiers" section in setLayout().
https://github.com/keyboardio/Chrysalis/blob/master/src/api/focus/keymap/db.js
2. ---> "for (const m of [0, 1, 2, 3, 6]) {" is missing indices 4, 5, and 7 which can be found in dualuse.js.
https://github.com/keyboardio/Chrysalis/commit/4d4d71c56b52f5d750a406af889e21bf7713fee5

**Expected behavior**
I expected the indices to match between the two files.

**Screenshots**
![image](https://github.com/keyboardio/Chrysalis/assets/58035835/d6d5b736-6947-4d2b-98fc-56bae469557e)
![image](https://github.com/keyboardio/Chrysalis/assets/58035835/7a2c2d54-2223-4e25-9de9-a9a246c64e85)

**Comment by obra** [comment]
Fixed
