### ISSUE TITLE
Update Firmware: What's New Link: Shows Blank Web Page

### ISSUE THREAD

**Issue by Zian** [keyboardio/Chrysalis#1326]
**Describe the bug**
After clicking the link to see "What's new in 0.92.2+104?", the browser shows a blank page.

**To Reproduce**

1. Go to the Layout & Colormap Editor Page:
    1. Start Microsoft Edge Version 122.0.2365.66 (Official build) (64-bit).
    2. Go to https://chrysalis.keyboard.io/.
    3. Click the CONNECT button.
    4. Click on the phrase "Model 100" in the popup.
    5. Click the blue Connect button.
    6. Wait until the keys of the keyboard appear.
2. Go to the Firmware Update page:
    1. Click on the hamburger menu.
    2. Click on "Firmware Update" in the "Keyboard" section.
3. Click the link labelled What's new in 0.92.2+104?".

**Expected behavior**
I expected to see what's new in version 0.92.2+104 of the Keyboardio Model 100 firmware.

**Screenshots**
![1 Update Firmware Page](https://github.com/keyboardio/Chrysalis/assets/1581929/302234ac-0399-4865-b992-4112f5144008)
![2 Blank Page](https://github.com/keyboardio/Chrysalis/assets/1581929/516493d5-ca6b-4919-9c20-c29dd01e85d5)

[Microsoft Edge DevTools Console After Clicking The Link.log](https://github.com/keyboardio/Chrysalis/files/14475653/Microsoft.Edge.DevTools.Console.After.Clicking.The.Link.log)

[Report a problem Page - Bundle.zip](https://github.com/keyboardio/Chrysalis/files/14475660/Report.a.problem.Page.-.Bundle.zip)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 22H2 (OS Build 19045.4046)
 - Chrysalis Version: Chrysalis 0.23.0821-dev

**Comment by obra** [comment]
Thanks so much for the detailed bug report. Replicated. Fixed.
I'm deploying a new version that should fix this issue now.
