### ISSUE TITLE
chrysalis.keyboard.io firmware update can't find device during "Entering programmable mode"

### ISSUE THREAD

**Issue by alunduil** [keyboardio/Chrysalis#1330]
**Describe the bug**
During the "Entering programmable mode" step of "Firmware Update," a dialogue titled "Connecting to your keyboard..." appears allowing me to click "OK" to get a device list. The resulting device list is empty on my system.

**To Reproduce**
1. Go to 'Firmware Update'
2. Click on 'UPDATE'
3. Hold "prog" key
4. Click "Continue"
5. "Connecting to your keyboard..." dialogue appears
6. Click "OK"
7. Browser dialogue appears with "No compatible devices found."

**Expected behavior**
Firmware update successfully completes.

**Screenshots**
![Screenshot 2024-03-20 12 31 22](https://github.com/keyboardio/Chrysalis/assets/169249/07102683-d71f-4acb-a94e-ada2f11016b3)
![Screenshot 2024-03-20 12 31 11](https://github.com/keyboardio/Chrysalis/assets/169249/c3b0f9ab-dc02-4768-9ca4-c8d8557b17cb)
BUNDLE: https://gist.github.com/alunduil/10f4d556ff53460d05eca932bf6f74a7

**Desktop (please complete the following information):**
 - OS: Google ChromeOS Version 122.0.6261.118 (Official Build) (64-bit)
 - Chrysalis Version: Chrysalis 2024.0318.1913

**Additional context**
This is the first firmware update I'm attempting on this Keyboardio Model 100.

**Comment by obra** [comment]
Hi Alex,

I don't have a current ChromeOS device here to test, but I've got some
guesses.

At the point where the empty device chooser pops up, is the prog key red?
If not, try disconnecting the keyboard and holding in the 'prog' key while
connecting it. Does it show up then?

If not:

 If you hold down the 'prog' key while plugging the keyboard into the
Chromebook, the Prog key should turn red. If you then load up Chrysalis and
try to connect, it will show an empty device chooser. Click "cancel" then.
Does the Model 100 show up when the second device chooser pops up?  (There
are some web platform limitations that don't let us probe your keyboard to
be able to show you only the correct device chooser.)

Best,
jesse

**Comment by alunduil** [comment]
Thanks, the following is how I got my firmware updated in case it's useful to others.

1. Browse to chrysalis.keyboard.io
2. Click "CONNECT"
3. Select "Model 100"
4. Navigate to "Firmware Update"
5. Click "UPDATE"
6. Hold "prog"
7. Click "CONTINUE"
8. At the next device prompt
9. Disconnect keyboard
10. Hold "prog" while reconnecting keyboard
11. Select bootable Model 100
12. Continue with firmware update as normal

Thanks for the pointers @obra

**Comment by obra** [comment]
Thanks so much for the update, Alex. I just created #1333 to track adding
better in-ui docs for this situation.

**Comment by nblumoe** [comment]
Thanks, the procedure described by @alunduil also worked with my Model01.
For the record: It was always shown correctly in the device picker, but it never starting flashing.

This is on macOS 14.4.1

**Comment by iGEL** [comment]
Just experienced the same bug on Linux Mint using Chromium. The instructions @alunduil shared in his 2nd post (disconnect + hold prog when reconnecting) helped. 👍
