### ISSUE TITLE
Linux udev rule installation instructions are incomplete.

### ISSUE THREAD

**Issue by parke** [keyboardio/Chrysalis#1344]
**Describe the bug**

The instructions for installing udev rules on Linux are incomplete.

**To Reproduce**

Go to https://chrysalis.keyboard.io/ without any udev rules loaded.

The instructions say:

>  As root, create a file called `50-kaleidoscope.rules` in the 
>  directory `/etc/udev/rules.d/` with the following contents: [snip]

>  Then, run `sudo udevadm control --reload-rules` to apply the new 
>  rules without requiring a reboot.

However, to actually apply the rules, the user must additionally do one of the following:

* Unplug and replug the keyboard, or...
* Run `sudo udevadm trigger`.

Neither of the above steps is included in the aforementioned instructions.

**Expected behavior**

I would expect to be able to connect to my keyboard after performing the steps listed in the instructions.

**Desktop:**
 - OS: Ubuntu Linux 24.04
 - Chrysalis Version: 2024.0518.0129

**Comment by obra** [comment]
Thanks. Fixed in 2024.0815.1830, which is deploying now.
