### ISSUE TITLE
how to improve the response of the palm key on Model 100

### ISSUE THREAD

**Issue by qliu-Inscopix** [keyboardio/Chrysalis#1345]
**Describe the bug**

Model 100:

My left palm key, set as a layer shift key, sometimes responds slowly when used with other keys, causing unintended solo activation of those keys. How can I fix this issue?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also include the debug bundle you can create on the "Report a problem" screen. If, for some reason, you are unable to access that screen, please press `Control + Shift + I` (Windows or Linux) or `Command + Option + I` (macOS) to bring up the developer console. Right-clicking inside it will allow you to save its contents to a file - please attach that to the bug report.

**Desktop (please complete the following information):**
 - Chrysalis Version: [e.g. 0.4.0]

**Additional context**

**Comment by obra** [comment]
It shouldn’t be possible for it to respond *slowly* although you may not be
getting it pressed all the way to the actuation point before hitting those
other keys. One possible solution would be to switch your palm keys to
kailh “speed” switches, which actuate much earlier in their keystrokes.

Jesse

**Comment by qliu-Inscopix** [comment]
Thank you. Speed switches sound promising.
