### ISSUE TITLE
The Globe key isn't working in macOS Sequoia.

### ISSUE THREAD

**Issue by NabiYang** [keyboardio/Chrysalis#1353]
**Describe the bug**
The globe key doesn't work alone and it doesn't work in shortcuts in macOS Sequoia.

**To Reproduce**
1. Assign the Globe key to a key using Chrysalis from the Control tab and the Mac / iPad keys section.
2. Save Changes.
3. Try using a Globe key shortcut with the keyboard connected to a computer running macOS Sequoia such as Globe+Q for Quick Notes.
4. ---> The Globe key doesn't work.

**Expected behavior**
I expect Quick Notes to open.

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.1
 - Chrysalis 2024.0830.2138

**Additional context**
I also tried the key in iPadOS 18.0. The key works erratically there. I can tap the Globe key to switch languages, but shortcut combos don't work.

**Comment by obra** [comment]
Unfortunately, Apple has been making changes that limit the ability of
third party keyboards to implement the globe key :/
