### ISSUE TITLE
Strings should be localizable

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#152]
It'd be lovely if our messages were in a message catalog, so the app is easier to internationalize (and to make it easier for a non-programmer to edit the text)

**Comment by algernon** [comment]
This is reasonably easy to accomplish, so I'm sticking it into the 0.3.0 milestone.

There are a few strings that come from elsewhere, which are going to be a bit more problematic (and I'd tackle them separately):
 - Key names, descriptions and whatnot (comes from `@chrysalis-api/keymap`)
 - Parts of the flashing instructions (comes from the hardware libraries)
 - Exceptions and error messages originating from libraries we use. These are mostly printed to the console though, and should likely stay as they are.
