### ISSUE TITLE
Notify the user when flashing fails due to a tool not available

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#156]
Some boards (ErgoDox & Atreus) are flashed with non-JS utilities, which at the moment need to be on PATH. We should tell the user this, and either point them to a place where they can download said utilities, or ship with apps for all the major platforms.

**Comment by obra** [comment]
Bundling the binaries, if allowed, for OSX, Linux and Windows is my
preference.

**Comment by algernon** [comment]
Should be, `teensy_loader_cli` is GPLv3, dfu-programmer is free software too, so we're good. Though, to be honest, seeing as they're all open source, I might just write a JavaScript library, and then we don't need to compile anything.

**Comment by algernon** [comment]
Looked at the `teensy_loader_cli` sources - it's fairly straightforward. I can probably implement it in JS in a few hours.

**Comment by algernon** [comment]
For 0.3.0, I'll go with having a note. We'll bundle/rewrite-in-JS for 0.4.0.
