### ISSUE TITLE
Can't flash new firmware

### ISSUE THREAD

**Issue by heliostatic** [keyboardio/Chrysalis#207]
I have a stock (unmodified firmware) Model 01 and am trying to use Chysalis for the first time.

Running Mac OS 10.14.2, usb-c to usb-c cable connecting keyboard to 2016 MacBook Pro.

Chrysalis correctly detects and connects to the keyboard, and then prompts to go to the firmware upgrade screen.

After clicking the firmware upgrade button, the spinner continues indefinitely. The keyboard appears to powercycle, and is quickly usable again.

The dev console shows the following, with no errors:
```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
App.js:167 Connecting to /dev/tty.usbmodemCkbio011
App.js:172 Probing for Focus support...
/Applications/Chrysa…rysalis-flash.js:35 baud update
/Applications/Chrysa…rysalis-flash.js:40 dtr on
/Applications/Chrysa…rysalis-flash.js:45 dtr off
/Applications/Chrysa…ib/connection.js:23 found Keyboardio Model 01 on port /dev/tty.usbmodemCkbio011
/Applications/Chrysa…no/lib/avr109.js:42 reset complete.
/Applications/Chrysa…no/lib/avr109.js:47 connected
```
Quitting the application and restarting puts me back at the beginning of this process.

**Comment by obra** [comment]
Ben,

Are you holding down the PROG key when trying to flash the firmware?

**Comment by heliostatic** [comment]
Ha, nope. I was not. That, of course, solved the issue. Thanks!

**Comment by obra** [comment]
Awesome! I'm so happy to hear it.

Sounds like we should make that bit of the UI clearer :)

**Comment by heliostatic** [comment]
I guess for folks new to flashing our keyboards like me :)

I did find one new issue after flashing: the white backlight mode appears to draw too much power.
<img width="367" alt="image" src="https://user-images.githubusercontent.com/70898/51288876-076b3500-19cc-11e9-9d50-3ce162ba5cbd.png">

**Comment by algernon** [comment]
I have to figure out how to add hardware-specific instructions to the flashing page. It does tell you to consult the hardware documentation about how to flash, but that's not a direct link, and isn't emphasized enough to make you go looking. I suppose we could have a Wiki page for Chrysalis, with links to the relevant hardware docs, and the firmware update screen could link to that (no need to make it hardware specific then!)

**Comment by algernon** [comment]
FWIW, the power draw is due to the Colormap plugin. keyboardio/Chrysalis-Firmware-Bundle#3 has a deeper explanation.

**Comment by obra** [comment]
I believe this specific issue is a support ticket, so I'm resolving it. #221 is the related engineering task
