### ISSUE TITLE
Improve OneShot support

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#210]
DualUse is integrated into the key selector much better than OneShot is. To make a modifier or layer key oneshot, one has to select the type, then re-select the modifier/layer - not exactly friendly.

Instead, we should have another dropdown, or a switch below the key type selector, and move DualUse stuff there too.

**Comment by algernon** [comment]
This will likely require another reorganization of the key selector component.

**Comment by qayshp** [comment]
Would also be nice to be able to enable `ActiveModColorEffect` for `OSM`/`OSL` from here... but sorry, I'm not sure if that would require a firmware change too.

**Comment by qayshp** [comment]
huh, just noticed that it is enabled... sorry! just not sure how to change the color :)

**Comment by algernon** [comment]
> just not sure how to change the color :)

That's only possible by changing the firmware at the moment. If you can file an issue on Kaleidoscope, requesting that `ActiveModColorEffect` should support changing the color via Chrysalis, that'd be great, and I wouldn't forget to implement it (it's pretty easy to do so).

**Comment by algernon** [comment]
Pushing this to 0.6.0 for now.

**Comment by algernon** [comment]
With the Editor redesign in 0.8.0, this has been addressed: OneShot layers appear together with the other layer keys on the sidebar:

![Screenshot from 2021-01-25 16-49-55](https://user-images.githubusercontent.com/17243/105729330-63f37a00-5f2d-11eb-82df-8d1afd2ba233.png)
![Screenshot from 2021-01-25 16-50-03](https://user-images.githubusercontent.com/17243/105729324-62c24d00-5f2d-11eb-8d12-2e3f8a6e1041.png)
