### ISSUE TITLE
Device chooser dropdown should be styled as a dropdown

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#214]
![image](https://user-images.githubusercontent.com/45416/51354744-7c407c80-1a69-11e9-8974-f642c15ddfec.png)

**Comment by obra** [comment]
Also grey, I think? https://material.io/design/components/menus.html#exposed-dropdown-menu

**Comment by algernon** [comment]
But it's not "exposed", not in its default state. The widget was modeled after [Selected Menus](https://material-ui.com/demos/menus/#selected-menus) in the library we use, but I can't find this in the Material Guidelines at the moment.

I'm not really fond of the grey background in this case... can't really explain why at the moment... I find it ok for things on the Settings page for example, but this feels different. The items are usually multi-line for one (second line being a port or "Unknown" in dimmer, smaller text).

**Comment by obra** [comment]
Let's see how we do with just the triangle, then.
