### ISSUE TITLE
Move "Connect" next to the thing we're connecting to.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#215]
![image](https://user-images.githubusercontent.com/45416/51354974-5b2c5b80-1a6a-11e9-8efa-1f1d0e4f4c1f.png)

**Comment by obra** [comment]
That's fine with me.

**Comment by algernon** [comment]
Hmm... rearranging things like that makes the keyboard icon lonely up top in the center. It looked fine with the dropdown being centered too. With the dropdown on the left, connect on the right... not so much. I can either remove it, integrate it into the dropdown (or move it onto the same line, left of the dropdown), or leave it in place in which case we'll figure out what to do with it later.

**Comment by obra** [comment]
Maybe put it to the left of the dropdown?

**Comment by algernon** [comment]
This feels much better to me:

![screenshot from 2019-01-18 09-32-21](https://user-images.githubusercontent.com/17243/51374658-fe7d7f00-1b03-11e9-8b20-2d5ddc168901.png)
![screenshot from 2019-01-18 09-32-44](https://user-images.githubusercontent.com/17243/51374671-089f7d80-1b04-11e9-964d-046459faaf89.png)

**Comment by obra** [comment]
That's acceptable to me :)
