### ISSUE TITLE
Firmware update page: describe the default better

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#219]
![image](https://user-images.githubusercontent.com/45416/51355501-3afd9c00-1a6c-11e9-8630-1f2793ac3b18.png)

**Comment by algernon** [comment]
I'll need help with this, I have no clue how it could be described better :(

**Comment by obra** [comment]
Sorry. The text was tiny below:

Even "Chrysalis default v0.31" would be ok. 

Or "Kaleidoscope-Chrysalis-`git desc`

**Comment by algernon** [comment]
Ooops! Didn't see the text. 'tis clear now, thanks!
