### ISSUE TITLE
Firmware update page: needs device-specific text

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#221]
We need a way to add a note telling the user to hold down the "Prog" key on the model 01

**Comment by algernon** [comment]
I had an [idea](https://github.com/keyboardio/Chrysalis/issues/207#issuecomment-455064745): point to a device specific Wiki page. The problem with device-specific text is that it should really live in the hardware lib, but that makes localisation harder. Not impossible, just a bit harder.

On second thought... we can have translations in the hardware libs too. Worst case? We'll have some untranslated text on the firmware update page.

**Comment by obra** [comment]
Pointing to a wiki page is insufficient. This has to be -easy- for novice users. 

Untranslated text is sufficient for now.
