### ISSUE TITLE
Transparent keys shouldn't say "Trns", they should just be empty

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#225]
![image](https://user-images.githubusercontent.com/45416/51356930-58813480-1a71-11e9-91c7-99b1356e03fd.png)

"Trns" doesn't communicate a whole lot, and is also the default state of keys. Let's try just making transparent keys not say anything.

**Comment by algernon** [comment]
What should blank (`Key_NoKey`) keys display as then?

One idea I had was to make it possible to have colors or textures on the keycaps, even in the layout editor (#155). That would allow us to have transparent keys blank and white, `NoKey` as blank with a grey-ish background.

**Comment by obra** [comment]
"No Key" as XXX (at least for now) makes sense to me. Once we're at the
point of colors and things, we could grey it out. but not important for now.

**Comment by algernon** [comment]
It's technically possible, all of the SVGs are set up to support both at the same time. It's just a matter of figuring out the appropriate colors, and adding a few lines to put the appropriate colors under keys that need it.

**Comment by obra** [comment]
*nod*  No-key as greyed out would also be acceptable

**Comment by TreTuna** [comment]
So, it sounds like this should be a change in https://github.com/keyboardio/chrysalis-api/tree/master/packages/chrysalis-keymap to mark NoKey as "XXX" and Transparent as "" (empty string). I can make this change, then I will look into working on https://github.com/keyboardio/Chrysalis/issues/155 to add some colors to the keys to distinguish different states.

**Comment by obra** [comment]
That makes sense to me

**Comment by algernon** [comment]
I have another bug to fix in `@chrysalis-api/keymap`, and will upload a release after that. Once Chrysalis updates its dependency, this issue should be fixed.

Thanks @TreTuna!

**Comment by algernon** [comment]
Indeed, thanks for the reminder!
