### ISSUE TITLE
Copy should be "copy from" rather than "Copy to"

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#226]
![image](https://user-images.githubusercontent.com/45416/51356984-95e5c200-1a71-11e9-9ab5-867625393195.png)

"Copy from" is closer to what the user is likely to want to do. "I have this layer. I want to make it like this other one"

Also, it makes you be on the screen with the layer being destroyed, which is much more likely to prevent the user from shooting themselves in the face.

**Comment by algernon** [comment]
Same applies to the colormap editor then. It's been tough to choose which behaviour to implement, and my first instinct was "Copy to...". Having used it, I agree, it should be "Copy from..." instead.

**Comment by obra** [comment]
*nod* It's never wrong to ask me for opinions in advance, but also, not all
that wrong to just try it one way ;)
