### ISSUE TITLE
At some point, Chrysalis should be able to flash a Model 01 from the bootloader. 

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#240]
This is useful if the user builds bad firmware and we need to flash from recovery

**Comment by algernon** [comment]
This is totally doable. Easiest way: have a Model01Bootloader device, with the bootloader PID, and flash it without reset.

This would, in practice, mean that Chrysalis would detect the keyboard as something that lacks features, go to the welcome screen, then update firmware, flash without reset, and boom, we can now select the Real Device.

A bit of a hack, but this is doable right now, without bigger changes to Chrysalis. To do it properly and support bootloader PID/VID pairs, we'd need to think a bit more.

**Comment by obra** [comment]
Having the hack now seems like a win.

**Comment by algernon** [comment]
I'll make it happen then.
