### ISSUE TITLE
Window to keymap resizing needs better consistency

### ISSUE THREAD

**Issue by TreTuna** [keyboardio/Chrysalis#251]
When resizing the main window, the UI of the keymap does not resize consistently. It starts off filling about 90% of the window, then shrinks drastically, then goes back to the previous size, then finally gets slightly larger. 

We should have this resize consistently to a maximum size and then stop. Perhaps working with the percentage of the screen vs media queries in order to avoid jumpy resizing.

Link to a video of the offending behavior: https://www.dropbox.com/s/jc9ee3vd6drro70/Screen%20Recording%202019-01-21%20at%205.07.36%20PM.mov?dl=0

**Comment by algernon** [comment]
There are some media queries in place, but they're kinda... wonky, indeed.

**Comment by algernon** [comment]
#267 is merged, closing this.
