### ISSUE TITLE
Adapt displayed keyname based on user's OS keyboard layout

### ISSUE THREAD

**Issue by hnrklssn** [keyboardio/Chrysalis#256]
Currently it is a very confusing process trying to configure a layout for use with a computer where the OS layout remaps the keys to other outputs than the US QWERTY. Ideally this would be an auto-discover feature, but my research into the issue suggests that might require some non-trivial cross-platform C++. A more pragmatic, but less elegant, solution would be to have a i18n-esque conversion table for different keyboard layouts, where the user gets to pick from a list.

**Comment by algernon** [comment]
I'm closing this, in favour of #513.
