### ISSUE TITLE
Unable to edit layers with EEPROM installed

### ISSUE THREAD

**Issue by compostbrain** [keyboardio/Chrysalis#259]
![2019-01-24 11 13 50](https://user-images.githubusercontent.com/13973110/51691787-74348f80-1fc9-11e9-8280-00a04c382a22.gif)

**Comment by TreTuna** [comment]
If you look at the layer tabs at the top you will see that the first three are marked with (RO), which means read-only. Your EEPROM layers start at layer 3. We're working on making this beginning workflow better, but for the moment I've found the best way to go about the initial setup is to do the following steps:

Copy layer 0 to layer 3 and mark this as the default layer
Copy layer 1 to layer 4
Copy layer 2 to layer 5
Change any "ShiftTo" and "LockTo" keys to mark new layers (1 becomes 4 and 2 becomes 5)
Sync this to your keyboard
Unplug and replug it in for the default layer change to take hold

**Comment by RickCogley** [comment]
I'm not one of the devs, but isn't the RO after the layer you have selected indicating it is Read Only?

**Comment by algernon** [comment]
> Unplug and replug it in for the default layer change to take hold

With the new default & experimental firmware this step is no longer needed, because Kaleidoscope switches to the default layer when it is set, without replugging.

**Comment by compostbrain** [comment]
Thanks for the explanation. It all makes sense now that I know what the (RO) means.

**Comment by algernon** [comment]
I'm closing this in favour of #297, which better describes what we need to do.
