### ISSUE TITLE
The experimental firmware should have compatible EEPROM layout

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#270]
Right now, the Model01 experimental firmware has an EEPROM layout that is not compatible with the default one: there's a palette before the keymap. Anything extra in the experimental firmware should come after the keymaps.

**Comment by obra** [comment]
I feel like this will be an ongoing problem. Should we have a way to force
ordering? I feel like our lives will be easier if EEPROM is easy to keep
stable between builds.
ᐧ

**Comment by algernon** [comment]
It shouldn't be much of a problem, once I add comments. Just have to remember to add stuff at the end and not in between, and we're good.

keyboardio/Kaleidoscope#344 will be some help, because we can then save the eeprom layout in Chrysalis, and if we see the same board again, with a different layout, we can either automatically rearrange if possible, or offer the user the choice.

**Comment by algernon** [comment]
Marking it pending, keyboardio/Kaleidoscope#557 has a fix, we just need to rebuild the firmware we ship with Chrysalis.

**Comment by algernon** [comment]
This is now waiting for keyboardio/Model01-Firmware#77. Once merged, I'll build new firmware.

**Comment by obra** [comment]
That's merged.
ᐧ
