### ISSUE TITLE
LayerEditor Tabs component should be aware if the RO tabs are hidden

### ISSUE THREAD

**Issue by TreTuna** [keyboardio/Chrysalis#301]
If a user has the RO layers hidden, it causes a non-breaking error to occur as the Tabs component get values for layers that do not exist at that time.

![screenshot 2019-02-06 14 40 01](https://user-images.githubusercontent.com/16496746/52379210-a9f06400-2a1e-11e9-8f5d-874abc564cda.png)

**Comment by algernon** [comment]
I *think* this only happens if the RO layer in question is set as a default. And that's because on `componentDidMount()`, we try to switch to the default layer, and do not account for it being possibly hidden.
