### ISSUE TITLE
Blank/white window after switching between color and keyboard layout

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#302]
While playing with Chrysalis I switched from the colormap editor to the layout editor, and the screen went blank. Log attached.

[-1549503166875.log](https://github.com/keyboardio/Chrysalis/files/2838981/-1549503166875.log)

**Comment by fluffy-critter** [comment]
Got what I think is a related crash from clicking outside of the hamburger menu to dismiss it. 
[-1549514529157.log](https://github.com/keyboardio/Chrysalis/files/2839336/-1549514529157.log)

**Comment by algernon** [comment]
I thought both of these would be fixed on master (by f6517e9f0864c137411049166c59b6bbf9e16a39), but apparently, there's still an issue somewhere. Thanks for the report!

**Comment by algernon** [comment]
This is hopefully addressed by #304.
