### ISSUE TITLE
Please show the key map on top of the colormap editor

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#303]
When I'm editing a colormap it's probably because I want to set the colors on a per-key-type basis. It'd be cool if the actual key labels were visible on the colormap editor (maybe greyed out to indicate they're not editable and outlined in white so they get forced contrast with the background color).

**Comment by TreTuna** [comment]
Hmm... I like this. Makes a lot of sense as well.

**Comment by obra** [comment]
Yes. This makes a lot of sense

**Comment by fluffy-critter** [comment]
Oh, and I'd also love it if there could be an "unset"/"passthrough" color so that in the case of layer stacking it just uses whatever would correspond with the key under it.

**Comment by algernon** [comment]
> Oh, and I'd also love it if there could be an "unset"/"passthrough" color so that in the case of layer stacking it just uses whatever would correspond with the key under it.

The Colormap plugin used to have a transparent color support, but it was very slow, and was [removed](https://github.com/keyboardio/Kaleidoscope-LED-Palette-Theme/commit/4a494c686bb26538140798178033b6b63ff0745f). It might be possible to do it better now, I'll file an issue on Kaleidoscope.
