### ISSUE TITLE
Experimental Model01 firmware: layer 1 still has the NumLock effect active

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#306]
When switching to layer 1 and using the experimental firmware, the NumLock LED effect still activates, overriding whatever color scheme is configured in Chrysalis.

Filed here because I don't see anywhere in the Model01-Firmware project that the experimental firmware for use with Chrysalis lives.

**Comment by fluffy-critter** [comment]
Moving to the correct repo

**Comment by qayshp** [comment]
Just wondering what repository (and issue number) you moved this to.
Thanks!

**Comment by fluffy-critter** [comment]
https://github.com/keyboardio/Chrysalis-Firmware-Bundle/issues/4
