### ISSUE TITLE
Long list of keys hide the dualUse switches

### ISSUE THREAD

**Issue by pdcawley** [keyboardio/Chrysalis#315]
If the list of keys in a category is long enough to wrap onto two lines, then the dual use toggle overflows the display and can't be seen.

**To Reproduce**

1. Go to 'Layout Editor'
2. Click on a letter key
3. At the default size on OS X, the list of possible keys wraps onto two lines and the switch labelled `Modifier when held, normal key otherwise` is clipped

**Expected behavior**
I expected to be able to enable dual use on letter keys. I only realised this was possible when I maximised the window. If the window is too narrow for all the options, I'd expect to see a scroll bar in the key selection area (or whatever the heck it's called).

**Screenshots**

* Two lines of keys:

<img width="912" alt="screenshot 2019-02-09 at 11 47 36" src="https://user-images.githubusercontent.com/5128/52520369-03e06c00-2c61-11e9-8ee5-f465a8046097.png">

* Wide enough for one switch to appear

<img width="1166" alt="screenshot 2019-02-09 at 11 53 04" src="https://user-images.githubusercontent.com/5128/52520384-44d88080-2c61-11e9-9ef1-14b4f4878641.png">

* Ooh! I didn't even know about this option!

<img width="1371" alt="screenshot 2019-02-09 at 11 54 04" src="https://user-images.githubusercontent.com/5128/52520391-68033000-2c61-11e9-92f2-e10615fbf2cc.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14
 - Chrysalis Version: 0.4.0 AND master

**Comment by TreTuna** [comment]
Mentioned this in Discord, however, I played around with moving things around and resizing the KeySelector and am not getting something I'm really liking with it yet. We may have to rethink the way these are incorporated.

**Comment by TreTuna** [comment]
Just commenting here that this is related to https://github.com/keyboardio/Chrysalis/issues/210

**Comment by mattvenn** [comment]
Perhaps I'm overlooking something, but why not just make the window bigger and the keymap smaller?

**Comment by algernon** [comment]
We have redesigned the Editor, so this is no longer applicable, the new editor does not have this problem.
