### ISSUE TITLE
Make it a little harder to clear the layer

### ISSUE THREAD

**Issue by pdcawley** [keyboardio/Chrysalis#316]
## Argh!

A couple of times now I've wiped the layer I'm working on by accidentally clicking twice on the `...` menu in the layout editor, because the option that appears under the mouse is 'Clear layer...', and there's no confirmation box when you take such a destructive action. 

Note that the ellipsis on the `Clear layer...` option implies that there will be some kind of further interaction before the layer's actually cleared.

### The Best Of All Possible Worlds Option

A working undo/redo system to allow stepping back and forward through the history of our changes.

### The 'Are you sure you want to do that, Dave?' quick and dirty solution

Pop up a dialog asking Dave if he's sure he wants to zap the current layer before zapping 

### The 'rearrange the deckchairs' not-really a solution

I initially thought a quick fix might simply be to reorder the menu so that 'Clear layer...' doesn't pop up under the mouse, but that's not really addressing the underlying problem that it's too easy to take destructive actions.

**Comment by algernon** [comment]
FYI, if you clear a layer, you can undo the clear (and everything else you have unsaved) by clicking the "X" the main menu turns into. Mind you, for a potentially destructive operation, a confirmation dialog is useful, so we'll be adding one (see #322, which has the dialog implemented).
