### ISSUE TITLE
Merge the colour editor with the layout editor

### ISSUE THREAD

**Issue by nickhandel** [keyboardio/Chrysalis#318]
Per this reply: https://community.keyboard.io/t/comparing-keyboardio-m01-and-ergodox-ez/933/53?u=nickhandel, merging the colour map editor with the layout editor would, I think, be a huge usability bonus (particularly since my colour map doesn't seem to work with 0.4.0 - shows all black (upgrade needed to that bit separately, perhaps).

IMO, whilst the LED effects are pretty (cycling colours etc.), I think it would be a more useful out-of-the-box default to have a colour per layer, with colours mapped to different types of key types (navigation, mouse, media etc.).  This is currently still slightly daunting (for a new user) to set up with Chrysalis given the two separate modes for colours and maps.  

Also IMO, the use of colour to denote modifiers etc. in the layout view would be confusing (I found it so with the Ergodox configurator that offers colour editing).  I think, the closer the software represents the physical view of the keyboard, the better.  I'd have thought shading, or something like a "dog-ear" corner on each key with a "special" config like one-shot or hold to modify would be more intuitive and would allow colours to mean colours.  There are four corners.  Or, you could colour-code the "dog-ear", which might be better. 

I'd have thought the UI to pick colours would be just another row with the eight basic colours at the bottom of the pane that pops up when you click on a key?  You could add an ellipsis to get to a more sophisticated set of colour options.  I'd imagine that most users just want basic colour options.  

Better still (for me, at least) would be to allow the user to assign a colour per "key type".  The result would be a very fast way of getting something visually useful, very quickly indeed.  This could just be a "key type colours" menu item.

To combine the two, you could have colours determined by key type (shown semi-transparently), but overridable for a specific key on a specific layer, which would show the colour as opaque.

Thanks!

**Comment by algernon** [comment]
This is *mostly* done, as in, we merged the colormap and layout editors. As such, I'll be closing this, but I'm also opening a few child issues, based on the ideas expressed here.
