### ISSUE TITLE
Default layer is not persisted after keyboard replug

### ISSUE THREAD

**Issue by szymonm** [keyboardio/Chrysalis#341]
**Describe the bug**
When I select some other layer than 0 for the default, then I replug the keyboard, the setting is gone.

**To Reproduce**
1. Go to keyboard settings and select layer 3 as default.
2. Unplug the keyboard and connect it again.

**Expected behavior**
I expect the layer 3 will be the default again.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Chrysalis Version: 0.4.0+77

**Comment by algernon** [comment]
There should be a "Save changes" button on the same page:

![screenshot from 2019-03-05 11-58-36](https://user-images.githubusercontent.com/17243/53800878-0c655300-3f3e-11e9-89b9-3386c9062c6a.png)

Without pressing the button, the changed default is not saved to the keyboard. Is the problem reproducible with the button pressed prior to unplugging the keyboard?

**Comment by szymonm** [comment]
Yes, it is the same even if I press the save button.

**Comment by szymonm** [comment]
Also after pressing "save changes" after few seconds the "Default layer" value is back to "No default".

**Comment by TreTuna** [comment]
This is probably the same bug I have been experiencing where it's not actually writing the default layer properly. @algernon, we talked a little about this in Discord and I was meaning to file this bug myself, but then my daughter was born and I forgot about everything, lol.

**Comment by algernon** [comment]
Reproduced, kinda. I can set the default layer to "layer 0" or "layer 1", but setting it to "layer 2" blows things up. There's nothing useful on the dev console.

**Comment by algernon** [comment]
This is likely a firmware issue, because setting layer 0, 1, and no default all work. Setting layer 2 and above seem to revert to no default.

**Comment by szymonm** [comment]
Weird, because it worked before, when the default layer was set in the layout tab. I used layer three and didn't have this issue. I'm using keyboardio. cc: @obra

**Comment by algernon** [comment]
Yeah, we (I) changed the firmware since, and that broke it. I have a fix incoming in a few minutes.

**Comment by algernon** [comment]
keyboardio/Kaleidoscope#596 addresses this, will close when I'm updating the shipped firmware.

**Comment by szymonm** [comment]
Thanks for the explanation! and for fixing of course!
