### ISSUE TITLE
Colormap editing doesn't work

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#352]
**Describe the bug**
Having a key selected, with the color editor active, clicking on a color from the palette sets the modified flag, but does not update the colormap itself.

**To Reproduce**
1. Go to the layout & colormap editor
2. Click on the palette icon on the toolbar
3. Select any key
4. Select any color from the palette
5. Observe that the appbar turns into a context state (modified flag is set), but the colormap does not update

**Expected behavior**
The selected palette color should be applied to the current key.

**Screenshots**
![Screenshot from 2019-03-14 10-37-38](https://user-images.githubusercontent.com/17243/54346395-3bb64700-4645-11e9-86b7-d78a89353f89.png)

There are no errors or relevant warnings on the dev console.

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Chrysalis Version: 0.5.0

**Additional context**
This is using my own custom firmware, but the error itself does not look like it would be firmware-related.

**Comment by pocketkk** [comment]
Same issue with experiemental firmware on mac os mojave.
