### ISSUE TITLE
Add ability to assign F13, F14, F15 and F16

### ISSUE THREAD

**Issue by ChristianKleineidam** [keyboardio/Chrysalis#353]
**Is your feature request related to a problem? Please describe.**
For triggering autohotkey scripts it's useful to be able to assign keys that otherwise don't get used. In many other application it's also possible to add new hotkeys but a lot of the existing hotkeys are already assigned. F13-F16 are great keys I would like to be able to assign for that purpose.

**Describe the solution you'd like**
In the same way the other F keys are able to be assigned F13, F14, F15 and F16 should be also able to get assigned.

**Comment by algernon** [comment]
Thanks, added the keys to the key database, Chrysalis will support them as soon as the `@chrysalis-api/keymap` dependency is updated.
