### ISSUE TITLE
Ability to add more then 5 layers

### ISSUE THREAD

**Issue by ChristianKleineidam** [keyboardio/Chrysalis#354]
Currently, I can only edit the 5 existing layers in Chrysalis and there no button to add additional layers.

**Comment by TreTuna** [comment]
Adding layers is something that must be done on the firmware side. This is simply not possible in Chrysalis, and I'm not sure if it will be possible (@algernon would know better).

If you need more than 5 layers you will currently have to create your own firmware to load.

**Comment by algernon** [comment]
Like @TreTuna said, there's no way to add new layers from Chrysalis, and no current plans to make it able to do so, thus, if you want or need more, you'll have to compile custom firmware at the moment.

It is technically possible to enhance the firmware so it allows creating additional layers, but that'd have way too many corner cases and error scenarios, so we didn't do it.
