### ISSUE TITLE
Blank screen after pasting layout and switching layer

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#363]
**Describe the bug**

Get a blank window after pasting a JSON layout from the clipboard

**To Reproduce**

1. go to layer 0, select copy/paste 
2. paste from clipboard
3. press 'okay'
4. go to layer 1

**Expected behavior**

Expected to be able to then edit layer 1

**Screenshots**

[localhost-1553201025958.log](https://github.com/keyboardio/Chrysalis/files/2993912/localhost-1553201025958.log)

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrysalis Version: 9cb6de1

**Additional context**

**Comment by mattvenn** [comment]
confirmed. Also I see this with copying to clipboard as well.

**Comment by obra** [comment]
This should not have been resolved if the patch was applied to Dygma's fork, but not the core.

**Comment by 0957758592** [comment]
It looks like this issue should be closed, cause were being merged.

**Comment by fluffy-critter** [comment]
As a note, if you put text like "Fixes #363" into the PR comment, then the issue will automatically close when the merge happens.

**Comment by 0957758592** [comment]
@fluffy-critter 
Thank you!
