### ISSUE TITLE
Wrong layer gets uploaded on import

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#364]
**Describe the bug**

Importing a layer to layer 1 puts it on layer 0 instead

**To Reproduce**

1. select layer 1 in the editor
2. go to import/export
3. paste layout
4. save to keyboard

**Expected behavior**

layout should be loaded to layer 1, not to layer 0

**Screenshots**

Before I overwrite the layer:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/347162/54785530-b7833700-4be3-11e9-847d-c67fa7dfa100.png">

UI after I overwrite the layer:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/347162/54785573-d255ab80-4be3-11e9-918c-f51bc36e5f1c.png">

Then I press "save to keyboard" and get another white-screen crash. And now I can't type on my keyboard. I relaunch Chrysalis and see this (I'm not even sure where it's getting *this* layout from actually):

<img width="912" alt="image" src="https://user-images.githubusercontent.com/347162/54785632-f1ecd400-4be3-11e9-86a9-bdefb96cb052.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrysalis Version: 9cb6de1

**Additional context**

**Comment by algernon** [comment]
Layout importing was quite.... buggy^Wbroken. We recently redesigned it, and it will import full layouts now, not individual layers. As such, this issue is no longer applicable.
