### ISSUE TITLE
Allow to set AltGr to a key

### ISSUE THREAD

**Issue by M5oul** [keyboardio/Chrysalis#371]
With bépo layout, `AltGr` is used a lot. I would like to set this modifier on a key from the palm.
Chrysalis, does not allow it.

**Comment by algernon** [comment]
`AltGr` is the same thing as `Right Alt`, which Chrysalis should be allowing you to set. Can you check if that works for you?

**Comment by M5oul** [comment]
Ah, yeah. It’s here. Why didn’t I saw it last time? Sorry. Thanks.
