### ISSUE TITLE
Make modifier checkboxes available to all key types 

### ISSUE THREAD

**Issue by leavesofgrass** [keyboardio/Chrysalis#376]
You can click a checkbox on a digit or a letter to add a modifier like Alt, Shift, or CTRL but this functionality isn't available to Miscellaneous keys like PrnScr or the Mouse button keys.

![misc_no_mods](https://user-images.githubusercontent.com/831808/56639622-f0b92780-6625-11e9-88c4-e6b42533c2a0.JPG)

Including these modifiers for all key types would be ideal in order to maximize mapping potential. 

(CTRL+SHIFT+PrnScr is also "copy a screenshot of the selected area to the clipboard" in Ubuntu.)

_On a related note_: Please consider treating Insert as such a modifier. It would be a huge plus for many people with disabilities because it is used so extensively with accessibility software as a critical modifier.

**Comment by Exitialis1** [comment]
I'd also like this, Alt + print screen is take a screenshot of the selected window in Windows and I prefer having that setup as a single key press.

**Comment by hnrklssn** [comment]
Seems closely related to this issue: https://github.com/keyboardio/Chrysalis/issues/257
Mostly commenting just to link them together.

**Comment by tmarzolf** [comment]
Alt + print screen would be specifically useful to me as well as very desirable as a single key press in Windows...

**Comment by obra** [comment]
I think the only limitation is that modifiers should not be available on consumercontrol/systemcontrol keys

**Comment by bjartek** [comment]
Yes please :)

**Comment by algernon** [comment]
This is now fixed on master, and in 0.8.1-snapshot.

**Comment by bjartek** [comment]
Thanks!
