### ISSUE TITLE
allow different keyboard layouts in one hardware type

### ISSUE THREAD

**Issue by mattvenn** [keyboardio/Chrysalis#378]
The Dygma Raise has ISO and ANSI versions. Hardware type can be queried via serial.

The configurator should automatically choose which key layout to display to the user.

Editor should send 

> hardware.ansi_iso

And will receive either:

> ANSI

or

> ISO

in return.

If ANSI, then use the ANSI svg layout to display keys and LEDs.
If ISO then use the ISO svg layout.

**Comment by TreTuna** [comment]
This could go in the right corner in replacement of the keyboard name tag that's talked about removing in https://github.com/keyboardio/Chrysalis/issues/385 or in the spot where the layers dropdown currently is if we move that over to join the other layer buttons.

**Comment by mattvenn** [comment]
It shouildn't need a control, because the configurator can request the type of hardware from the keyboard.

**Comment by mattvenn** [comment]
OK, we now have working keymaps for the ANSI and ISO version of the Raise here: https://github.com/Dygmalab/chrysalis-api/tree/cafa064a7a680e3a41c7d4bf5f0508a3b22199c5/packages/chrysalis-hardware-dygma-raise/src/lib/components

**Comment by mattvenn** [comment]
As I can't seem to link to discord messages, here's a discussion from the chrysalis group:
![image](https://user-images.githubusercontent.com/634220/58623849-2d380d00-82cf-11e9-819f-d2fb8659f76e.png)

We already have the focus hook as described above. This should be called after the focus.help command to determine which keyboard is used.

https://github.com/Dygmalab/chrysalis-api/tree/master/packages/chrysalis-hardware-dygma-raise needs splitting into ANSI and ISO versions, and the correct one should be loaded depending on the answer from the hardware.

**Comment by 0957758592** [comment]
Look through reference [here](https://github.com/keyboardio/chrysalis-api/pull/22#issuecomment-505835316)

**Comment by mattvenn** [comment]
this has now been fixed with 2 versions of our hardware and the new hardware.layout focus command
