### ISSUE TITLE
Add bossa firmware update

### ISSUE THREAD

**Issue by mattvenn** [keyboardio/Chrysalis#380]
Dygma Raise uses the SAMD21 chip from Atmel. The bootloader is based on the Arduino Zero, which uses bossa to upload new hex files.

Currently this is the line in the makefile that updates the firmware:

bossac -i -d --port=${DEVICE_PORT} -e -w ${BUILD_PATH}/${FIRMWARE}.bin -R

bossac will need to be packaged for windows, linux and mac.

Added complication: The SAMD21 doesn't have EEPROM, it does "emulated EEPROM". Which means that before flashing new firmware, the settings need to be read out of EEPROM and stored. Then after flashing the new firmware, restoring the settings.

**Comment by mattvenn** [comment]
found a pure javascript implementation of sam-ba here: https://github.com/synthetos/node-sam-ba/blob/master/sam_ba.js
will test on the Raise

**Comment by obra** [comment]
(license for this is GPL3. @algernon - how does that play with the license
regime for chrysalis?)
ᐧ

**Comment by algernon** [comment]
chrysalis-api (and Chrysalis itself) is GPL-3-only, that plays nice with GPL3+, so as far as licensing is concerned, `node-sam-ba` is fine.

**Comment by mattvenn** [comment]
we are now testing a fix for this - will submit a PR once we're happy

**Comment by algernon** [comment]
We have recently removed Raise support from Chrysalis, so this issue is moot now. If/when we re-introduce support for the Raise (or any other keyboard that uses Bossa), we'll add the appropriate flasher too.
