### ISSUE TITLE
Improve key selection highlight

### ISSUE THREAD

**Issue by mattvenn** [keyboardio/Chrysalis#383]
Currently the key highlight when selected is very difficult to see:

![image](https://user-images.githubusercontent.com/634220/56971087-d96bc400-6b68-11e9-8157-8a9a114c51d2.png)

Left is unselected, right is selected.

Suggestion, increase border of the key to 3px so it also has an obvious size difference:

![56971087-d96bc400-6b68-11e9-8157-8a9a114c51d2](https://user-images.githubusercontent.com/634220/57229119-a49eb780-7015-11e9-89e6-480e9f1b6cec.png)

**Comment by TreTuna** [comment]
This will actually have to be done for each `Key` component, in each keyboard, in https://github.com/keyboardio/chrysalis-api

**Comment by mattvenn** [comment]
OK, just found this myself. Thanks.

**Comment by mattvenn** [comment]
OK, this was an easy fix I did myself that just affects the Dygma keyboard.
