### ISSUE TITLE
reorganise colour picker and saved colours

### ISSUE THREAD

**Issue by mattvenn** [keyboardio/Chrysalis#384]
The saved colours should all be in one group. Having a separate group each side of the colour picker is confusing.

Recommend this layout as an example:
![image](https://user-images.githubusercontent.com/634220/57141174-ec290780-6db9-11e9-8be2-fe2e9ea2a78d.png)

**Comment by TreTuna** [comment]
This is the library we use for our color picker. http://casesandberg.github.io/react-color/

I had been looking at the _sketch_ version color picker on there for implementing with Chrysalis, though it takes up a lot of vertical space so the UI design would have to be changed for this.

**Comment by TreTuna** [comment]
![image](https://user-images.githubusercontent.com/16496746/57175036-05eb3e80-6dfc-11e9-9611-1d27b1dd64da.png)

**Comment by algernon** [comment]
Lets tackle this in #381, palette layout and the color picker are fairly tightly coupled, so I think one issue about them is enough, and #381 had more ideas laid out.
