### ISSUE TITLE
avast sees Chrysalis as a virus - hard to install on windows

### ISSUE THREAD

**Issue by mattvenn** [keyboardio/Chrysalis#394]
![image](https://user-images.githubusercontent.com/634220/58638038-2a034800-82f4-11e9-810c-14b9e06123d9.png)

What do we need to do to make this easily install on Windows?

**Comment by 0957758592** [comment]
Im calling in AWAST directly now (+18443409251) to solve it to add our product into their whitelist.. Will provide a response from soon.

**Comment by 0957758592** [comment]
> Im calling in AVAST directly now (+18443409251) to solve it to add our product into their whitelist.. Will provide a response from soon.

Waiting for reply from avast withing 24 hours.

**Comment by obra** [comment]
-Why- does it see it as a virus? (What does 'more detail' tell you?)
ᐧ

**Comment by tsh-xx** [comment]
Symantec warned me that the executable had only been seen 4 times when I installed a few weeks ago. So it isn't (for me) detecting a problem, just being overly cautious - I don't remember the exact dialogue, but it was moderately scary. It was trivial to allow installation though.

**Comment by mattvenn** [comment]
This is result of clicking on more details

![](https://files.slack.com/files-pri/T2D0XNG3C-FL0LSJHPE/screenclip__2_.png)

![](https://files.slack.com/files-pri/T2D0XNG3C-FL39GC5FG/screenclip__3_.png)

It's easy to turn off the antivirus then install.
Does anyone know how this stuff works? Will each new version of the executable need to be added to the antivirus databases for this issue to be resolved?

**Comment by algernon** [comment]
Perhaps signing the executable would get rid of the warning? Both Windows and macOS seem to be pushing hard towards signed installers. I suppose antivirus software would do likewise.

**Comment by algernon** [comment]
I'm not sure we can do anything about it on our end, and we didn't have other reports of anti virus software causing issues, so I'm going to close this issue.
