### ISSUE TITLE
Install via brew on Mac

### ISSUE THREAD

**Issue by miki725** [keyboardio/Chrysalis#399]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Would be wonderful to be able to install via `brew` on a Mac

**Describe alternatives you've considered**
Manual installation but ability to automate installation would be really great

**Comment by mattmc3** [comment]
@miki725 - I can take this one. It's not too tough to add a new app to `brew cask`. I'll update when I have a PR.

https://github.com/Homebrew/homebrew-cask

**Comment by mattmc3** [comment]
The Homebrew Cask PR has been merged. I vote to close this issue.

```
brew update && brew upgrade
brew cask install chrysalis
```

**Comment by obra** [comment]
Thank you!
