### ISSUE TITLE
Import export issue with Dvorak layout

### ISSUE THREAD

**Issue by mscottford** [keyboardio/Chrysalis#425]
**Describe the bug**
The Dvorak layout that's provided via the import/export screen is missing the color map. When you click the "Load a default" button for Dvorak and then click "OK", all of the keys still show Qwerty and the "Save changes" button is disabled. I'm guessing that's because without the colormap specified, the content in the text field is not valid.

To discover and work around this, I used the "copy to clipboard" button to copy the text from the import/export screen before clicking the "Dvorak" button and pasted it into one side of a blank text comparison in Meld. In the other side, I pasted in the contents after I clicked the "Dvorak" button. I then scrolled down to where the colormap is specified and used Meld's "copy to the right" feature to merge that chunk of text into the Dvorak version of the JSON. I then copied the modified text into the clipboard, and used the "paste from clipboard" button back Chrysalis. Then after clicking the "OK" button, all of the keys had been updated and the "Save changes" button was enabled and flashing the keyboard worked fine.

**To Reproduce**
Steps to reproduce the behavior (assuming that keyboard is flashed with Qwerty layout)
1. Click on 'Import/export' button.
2. Click on 'Dvorak'
3. Click 'OK'
4. Visual keyboard still shows Qwerty layout and there is no indication that changes have been made and the "save changes" button is disabled

**Expected behavior**
Dvorak layout should be displayed on the visual keyboard and the red bar should be visible to indicate that there are changes and the "save changes" button should be enabled.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Chrysalis Version: 0.6.2

**Comment by SylvainJunca** [comment]
I have the same issue

**Comment by algernon** [comment]
I believe this is no longer an issue, we fixed it sometime since the report came in.
