### ISSUE TITLE
Unable to turn off Space Cadet mode

### ISSUE THREAD

**Issue by nitishinskaya** [keyboardio/Chrysalis#427]
**Describe the bug**
I have a new Keyboardio that I just put the Chrysalis experimental 0.6.2 firmware on. Unfortunately space cadet seems to be permanently enabled and I can't disable it.

**To Reproduce**
1. Use my keyboard
2. Flash experimental 0.6.2 and set the layout to have two shifts (eg the default).
3. Press right shift without a following character and observe ) typed. Press left shift without a following character and observe ( typed.
4. Add space cadet enable and disable to the layout.
5. Press your SpaceCadet Disable key and repeat step 3.
6. Press your SpaceCadet Enable key and repeat step 3.

**Expected behavior**
No space cadet by default or when I explicitly disable it.

**Desktop (please complete the following information):**
 - OS: macos high sierra
 - Chrysalis Version: experimental 0.6.2

**Comment by CYblK4** [comment]
I also have this problem on the same keyboard on 0.6.2+124 experimental firmware. I'm on Windows 10.
Mapping a key to disable SpaceCadet and pressing it doesn't disable the feature.

**Comment by gijja** [comment]
It is odd, the only way that I could find to eliminate Space Cadet is to 

1. Disable space cadet, then save.
2. Reassign the key to right or left shift, as the case may be.
3. Make the key a one shot modifier.

Space Cadet is gone, but the key is now a OSM.

Also using High Sierra.

**Comment by px0** [comment]
Same problem

**Comment by CYblK4** [comment]
I've found a work around for this. Put a shift modifier on your shift key.

**Comment by gadzin1203** [comment]
> I've found a work around for this. Put a shift modifier on your shift key.

That worked for me, thanks! My shift keys are now S+RShift and S+LShift and I no longer get space cadet parens.

**Comment by algernon** [comment]
All of the firmware we ship with nowadays - whether default or experimental - comes with SpaceCadet disabled, if the plugin is even included in the firmware, so this should not be a problem anymore.

Additionally, in the near future, we'll be overhauling the features supported by our default & experimental firmware files, and SpaceCadet is likely getting dropped, further reducing the chance of this problem resurfacing.

As such, I'm closing this issue.
