### ISSUE TITLE
Simplify the key type dropdown by combining the various "mouse" options.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#447]
The keytype dropdown is...very comprehensive. Anything we can do to reduce the number of options without overpowering the character chooser is a win.

One small win is to combine Mouse {Button,Move,Wheel,Warp} into a single screen, adding the type of action as the first word of the label. "END" would become "WARP END", for example.

**Comment by aspiers** [comment]
See also #386.

**Comment by algernon** [comment]
I think the editor rework in 0.8.0 addressed this, at least for the most part.
