### ISSUE TITLE
Layer-related functions in the "Key type" dropdown could be simplified.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#448]
https://i.imgur.com/meeLAOd.png

The list of layers should be limited (and extended) to the range of layers we actually have set up on this device. (In this example, we have layer -4 on the device, but don't have a layer 16 ;)

Also, "shift to layer" and "lock layer" should be combined to a single menu item.  We've got space for two rows of "Shift to 1" and "Lock to 1"  as entries, if we limit to the number of layers actually on the device.  Once users have many more layers routinely, we can reevaluate the UI.

**Comment by algernon** [comment]
I think this has been addressed with the editor rework.
