### ISSUE TITLE
Keyboard detection not working on Gentoo Linux

### ISSUE THREAD

**Issue by edannenberg** [keyboardio/Chrysalis#459]
**Describe the bug**
Model 01 Keyboard not detected on Gentoo Linux

**To Reproduce**
1. Start Appimage on Gentoo Linux
2. Scan for keyboards shows `No keyboards found!`

**Expected behavior**
Model 01 Keyboard is detected

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Chrysalis Version: 0.6.2+132

**Additional context**
dmesg and the shell the appimage was started from show no errors at all. The keyboard itself is working and detection/mapping via Chrysalis works on Windows on the same box (dual boot). I run a fairly minimal kernel so it's likely I'm missing a required option, it's impossible for me to tell though.

**Comment by algernon** [comment]
Does the user you run Chrysalis with have permission to access the serial port of the Model01? (`/dev/ttyACMx`)

Or, since you're running a minmal kernel: does the serial port even show up? If not, you may need USB serial support in the kernel.

**Comment by edannenberg** [comment]
Thanks for the swift reply! Adding `CONFIG_USB_ACM=y` resolved the detection issue. When trying to connect the keyboard the app now states that a firmware update is needed. I already did the firmware update when trying this on windows. Is this normal when switching the OS or might there be another issue?

**Comment by algernon** [comment]
Then it's either permissions, or something (like ModemManager) interfering.

**Comment by edannenberg** [comment]
I added my account to the `uucp` group so it should have had permissions, maybe it wasn't active yet. After a quick `chown` on the device to my account everything seems to be in order now. Thanks!

Would be nice if the app would throw proper error message for these cases:

* `/dev/ttyACM` is missing => ensure `CONFIG_USB_ACM` is active
* the current user account doesn't have the required permissions to access the device

**Comment by algernon** [comment]
Yeah, better error messages is something we're working on. (See #276, for example)
