### ISSUE TITLE
In dark mode, title bar should be white text

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#471]
![tb2](https://user-images.githubusercontent.com/45416/75821079-76335b00-5d52-11ea-9f48-d698bdd8735a.png)
![tb1](https://user-images.githubusercontent.com/45416/75821082-76cbf180-5d52-11ea-937d-0c071a21f005.png)

**Comment by Rom1deTroyes** [comment]
The title seems good on Chrysalis-0.7.9.AppImage, 

![image](https://user-images.githubusercontent.com/8625432/86517921-2c0bd480-be2d-11ea-8e02-b1a6e56869cd.png)

**Comment by algernon** [comment]
This has been fixed for a while now, closing.
