### ISSUE TITLE
Only show available layers for selection

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#473]
**Describe the bug**
When setting up a layer select key (lock, shift, oneshot or any other variant), the key selector will offer all 32 layers as a possibility, even if the keyboard doesn't support that many.

**Expected behavior**
Chrysalis should only offer as many layers as available.

**Additional context**
We should also consider what happens if we end up with a keymap where we have a layer key pointing to an unavailable layer. We should still display that on the keymap, of course, but... what would be shown in the selector then?

**Comment by pm0u** [comment]
Where would the data be available for how many layers a keyboard supports or has? within focus somewhere?

**Comment by algernon** [comment]
If you ask the keyboard for `keymap.map` (via chrysalis' API), that'll get you an array of keys for each layer. So the size of the array is the number of layers the keyboard supports. (At least in 99.9% of cases... there are a few crazy edge cases where there will be more layers than what that command returns, but that's something we shouldn't care about.)

**Comment by algernon** [comment]
Actually, this is roughly how to get the # of layers:

```js
const getNumLayers = async () => {
  let focus = new Focus();
  let keymap = await focus.command("keymap");
  let layers = keymap.custom.length;
  if (!keymap.onlyCustom) layers += keymap.default.length;

  return layers;
}
```

**Comment by algernon** [comment]
#512 fixed this, closing.
