### ISSUE TITLE
"LockTo" and "ShiftTo" look wrong

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#474]
**Describe the bug**
The "LockTo" and "ShiftTo" top labels for layer keys feel a bit awkward.

**Expected behavior**
We should have a space between the two words.

**Comment by pm0u** [comment]
I did this quickly on an atreus screen, and the text is a _little_ long on shift to and unfortunately SVGs don't support text wrapping. I'm not sure what this would look like on other keyboard models as well. It could be possible to split up the text to 2 lines, or to shrink the text ever so slightly.
![image](https://user-images.githubusercontent.com/410558/80870646-0adc0b80-8c65-11ea-8969-b71d394bb4b9.png)

**Comment by obra** [comment]
This generally looks better now
