### ISSUE TITLE
How to remove the firmware of chrysalis

### ISSUE THREAD

**Issue by wimstockman** [keyboardio/Chrysalis#482]
I try to upload a modified ino.
Which says succes but my keyboards layout doesn't change it is still usig the crysalis layout.

How can I remove it.
I m on Linux Mint

kind regards
Wim

**Comment by algernon** [comment]
The layout doesn't change, because the firmware will prefer whatever is in EEPROM over what's in the firmware. By resetting EEPROM, the firmware layers will take priority.

To change that, go to Preferences, and turn off "Use custom layers only".

**Comment by wimstockman** [comment]
ok thank you , for the quick reply
