### ISSUE TITLE
Add a 'debug log" link in lower right corner of screen.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#491]
I wonder if we could stick a tiny link in the lower right corner that says "Debug log" which opens a text area with the contents of the console.

**Comment by algernon** [comment]
There's a few things that make this harder than one would like... first of all, the lower right corner is where the "Save" button is on the layout & colormap editor screen. We do not want to conflict with that.

The other is, I'm not sure how I can capture the console contents from the webapp. The best I can do, I think, is to listen to the `console-message` events on the webView, and display that when the debug log button is clicked. In some ways, this is likely friendlier than capturing _all_ dev console output. I will need to check if it captures everything we're interested in, though.

**Comment by algernon** [comment]
Well, `console-message` is... okay-ish? As long as we log formatted messages, we're good. I can capture that stuff within the app. Now the question is, where to put the debug button and the contents?

I was thinking, we could have a key binding instead - though that's not very discoverable. Or we could provide a button on the error notification and on the keyboard select screen. On the error notification, because we're mostly interested in the logs when there are errors. On the keyboard select screen, because that's the first screen, we have space there, so we can pop the logs up there in case the error notification did not display.

**Comment by algernon** [comment]
Current status on the [debug/log-viewer](https://github.com/keyboardio/Chrysalis/tree/debug/log-viewer) branch:

![Screenshot from 2020-04-02 13-59-31](https://user-images.githubusercontent.com/17243/78246921-39da5280-74ea-11ea-8104-59878e96c387.png)

---

![Screenshot from 2020-04-02 13-59-36](https://user-images.githubusercontent.com/17243/78246919-38a92580-74ea-11ea-9846-92c6407027c1.png)

**Comment by obra** [comment]
We can certainly move the button to the lower left corner to make it not
conflict with things.. And possibly make it even lighter grey

ᐧ

**Comment by algernon** [comment]
Lower left might be an issue with the key group dropdown, but much less so. The dropdown will simply hide the button, so we're ok.

If we want to deemphasize it, I can remove the outline. I'm not sure we should be playing much with colors - the ones provided by material UI are in general well thought out, imo.

**Comment by obra** [comment]
Yes, removing the border is great.  we can always play with the location later

**Comment by algernon** [comment]
Current status:

![Screenshot from 2020-04-02 22-22-10](https://user-images.githubusercontent.com/17243/78297735-7e88dc80-7530-11ea-817d-60b97d73e6fd.png)
![Screenshot from 2020-04-02 22-22-04](https://user-images.githubusercontent.com/17243/78297761-8cd6f880-7530-11ea-9558-95b3ef137bb2.png)

We're a bit off on some screens though:

![Screenshot from 2020-04-02 22-21-55](https://user-images.githubusercontent.com/17243/78297784-97918d80-7530-11ea-9f23-a004465079a2.png)

**Comment by algernon** [comment]
I think this is obsolete with #575? The system info screen allows us to view debug logs, and even makes a bundle for easy sharing, so it's a better way to get logs to us.

**Comment by obra** [comment]
yup
