### ISSUE TITLE
0.75 macos - random disconnects.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#521]
Seeing this in the log with an Atreus connected:
renderer.js:83 focus.request: keymap.onlyCustom
renderer.js:83 focus: incoming data: .
renderer.js:83 focus: incoming data: 1 
2
renderer.js:83 focus: incoming data: .
renderer.js:83 focus.request: settings.defaultLayer
index.html:1 Uncaught (in promise) Error: Error: Device not configured, cannot flush
index.html:1 Uncaught (in promise) Error: ENXIO: no such device or address, write
renderer.js:83 focus.request: keymap.default
renderer.js:83 focus.request: settings.defaultLayer
renderer.js:83 focus.request: led.brightness
renderer.js:83 focus.request: idleleds.time_limit
2
events.js:180 Uncaught Error: Port is not open
    at SerialPort.flush (/Applications/Chrysa…am/lib/index.js:524)
    at webpack:/src/api/focus/index.js:240
renderer.js:83 focus.find: portList: 
Array(1)
 devices: 
Array(9)
renderer.js:83 focus.find: found_devices: 
Array(0)
4
index.html:1 Uncaught (in promise) Communication timeout
events.js:180 Uncaught Error: Port is not open
    at SerialPort.flush (/Applications/Chrysa…am/lib/index.js:524)
    at webpack:/src/api/focus/index.js:240
renderer.js:83 focus.find: portList: 
Array(1)
 devices: 
Array(9)
renderer.js:83 focus.find: found_devices: 
Array(0)
events.js:180 Uncaught Error: Port is not open
    at SerialPort.flush (/Applications/Chrysa…am/lib/index.js:524)
    at webpack:/src/api/focus/index.js:240
renderer.js:83 focus.find: portList: 
Array(1)
 devices: 
Array(9)
renderer.js:83 focus.find: found_devices: 
Array(0)
renderer.js:83 focus.find: portList: 
Array(2)
 devices: 
Array(9)
renderer.js:83 focus.find: found_devices: 
Array(1)
renderer.js:83 Connecting to /dev/tty.usbmodemCatreusE1
renderer.js:83 Probing for Focus support...
renderer.js:83 focus.request: help
renderer.js:83 focus: incoming data: keymap.custom
keymap.default
keymap.onlyCustom
renderer.js:83 focus: incoming data: help

**Comment by algernon** [comment]
Is this still a problem?
