### ISSUE TITLE
0.75 macos - when you disconnect a keyboard, CPU spins out of control

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#522]
When a keyboard is connected to Chrysalis and you disconnect the keyboard's USB cable, Chrysalis' UI goes completely blank and the host's CPU spins out of control, presumably it's in a tight loop trying to probe for the keyboard.  

Instead, after 10-15 seconds, at the very least, we should end up back at the device chooser screen.

**Comment by daveanderson** [comment]
Still occurs with 0.79
