### ISSUE TITLE
Linux arm64 support

### ISSUE THREAD

**Issue by jwillikers** [keyboardio/Chrysalis#524]
**Is your feature request related to a problem? Please describe.**
I'd like to update my keyboard firmware using Chrysalis on my Pinebook Pro, which runs Manjaro on arm64 processors.

**Describe the solution you'd like**
I would like to be able to download an AppImage for arm64 and run it on the Pinebook Pro.

**Describe alternatives you've considered**
I could use another computer, use the Arduino IDE, emulate x86_64, or attempt to compile from source. However, none of these alternatives are ideal or convenient for an end user.

**Comment by skyfaller** [comment]
Have you tried compiling from source by installing https://aur.archlinux.org/packages/chrysalis-git/ from AUR via e.g. [yay](https://github.com/Jguer/yay)? Just curious if it works.

Clearly it would be more convenient to have a binary for ARM64, but when AUR works, compiling from source just requires some waiting. I've had to compile a lot of more obscure software for my PBP. It's when the AUR package doesn't compile successfully, and I have no idea why or how to fix it, that I start to get frustrated and wish there were an official binary.

**Comment by jwillikers** [comment]
@skyfaller That's a great idea, thanks for the suggestion. 👍
Unfortunately, no dice. 🎲🎲
I changed the architecture to `any` but the script ultimately failed.
Pulling down the latest source and using `yarn build:linux` creates an AppImage which works like a charm.

**Comment by algernon** [comment]
Things build fine on Travis, all I have to do now is fix the uploads, so that the Linux x64 and amd64 builds don't overwrite each other.
