### ISSUE TITLE
Make modifier checkboxes available to Print Screen or Miscellaneous category

### ISSUE THREAD

**Issue by tmarzolf** [keyboardio/Chrysalis#529]
Alt + Print Screen is commonly used to take a screenshot of an active window in Windows. Would be nice if this specific combination could be assigned to a key from Chrysalis . 

Could be addressed by making modifier checkboxes available in the Miscellaneous category or moving / duplicating Print Screen into a category that already contains checkboxes (Punctuation or Spacing?)

This is a specific instance of the more general:
https://github.com/keyboardio/Chrysalis/issues/376

Separate request added with hopes this specific item is easier to action than the broad request.

**Comment by algernon** [comment]
This is now fixed on master, and in 0.8.1-snapshot.
