### ISSUE TITLE
Blank screen after flash clean firmware on Atreus (0.75)

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#531]
I recognize that 0.75 is not current, but wanted to capture an issue I'd seen reported but never experienced myself.

After flashing an Atreus on macOS on 0.75, including wiping the EEPROM, I clicked "connect, saw the blank atreus keyboard layout indicating loading, and then the screen when white.

This is what was in the dev tools:

![image](https://user-images.githubusercontent.com/45416/85455807-2839a180-b553-11ea-9c18-0e4f6ac8dbfe.png)

**Comment by algernon** [comment]
I _think_ this happened due to partial loading. With the new loading screen, this shouldn't happen. I'm inclined to close this, and reopen if someone manages to reproduce the problem again.

**Comment by obra** [comment]
ok
