### ISSUE TITLE
way to identify firmware version currently on device

### ISSUE THREAD

**Issue by qayshp** [keyboardio/Chrysalis#533]
**Is your feature request related to a problem? Please describe.**
Not so much a problem as a small annoyance.
I have no way to know which firmware is currently running on my Keyboardio (flashed from Chrysalis). For example the version, `0.7.7` vs `0.7.6`, or `default` vs `experimental`.

**Describe the solution you'd like**
Some kind of indication of what was last flashed to the device.
For example:
-  `0.7.7 experimental`
-  `0.7.6 default`

**Describe alternatives you've considered**
Writing down or remembering what I did last.

**Additional context**
I know there will be complications with custom firmware bundles.

**Comment by algernon** [comment]
The easiest way to do this is to embed the version in the firmware, and query that from Chrysalis. I have a [plugin](https://git.madhouse-project.org/algernon/Kaleidoscope-Focus-Version) that makes this slightly easier, but it's a bit tricky to use in official firmware.

**Comment by algernon** [comment]
We have a FirmwareVersion plugin now, which will be enabled in the firmwares Chrysalis ships with. Once the updated firmware files are merged, I'll rework the FirmwareUpdate screen a little to show the currently running firmware version too (if available).

**Comment by algernon** [comment]
A little progress update:

![Screenshot from 2022-06-26 15-25-44](https://user-images.githubusercontent.com/17243/175816314-40d595d6-0908-42bb-ad47-6b9abd2bd464.png)
