### ISSUE TITLE
FR: make it easier to blank keys

### ISSUE THREAD

**Issue by aspiers** [keyboardio/Chrysalis#539]
When setting up a new keyboard, I typically want to make major changes to the default layout.  In many cases this means blanking out many keys (i.e. setting to blocked or transparent), either permanently, or at least temporarily while I figure out what to put on those keys, because it is less confusing to start with a blank canvas and gradually add mappings, than to be staring at a horrible mix of default and customised mappings.

However currently it is quite slow to make keys blocked or transparent, since for each key you have to tap on the `Key type` chooser, then scroll down to Blank (due to #386), then select the mapping.

So I would suggest two new options:

- When a key is selected, make Backspace set that key to transparent, and Delete set it to blocked (or something along these lines).
- When a key is right-clicked, offer both blocked and transparent in the drop-down menu.

**Comment by obra** [comment]
Backspace to blank makes sense to me. I don't think we need the affordance of Delete to Blocked. (I don't believe blocked is going to be frequently used enough to make sense with the high-level affordance.)
