### ISSUE TITLE
Oneshot modifiers menu missing "RIGHT SHIFT" in Chrysalis 0.7.9

### ISSUE THREAD

**Issue by tmarzolf** [keyboardio/Chrysalis#548]
**Describe the bug**
Right Shift should be included in the "OneShot modifiers" menu

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrysalis Version: [e.g. 0.7.9]

**Screenshots**

![image](https://user-images.githubusercontent.com/63314904/89682671-1c1c6000-d8c5-11ea-9101-9cbacfca5bce.png)

**Additional context**
 This appears to have existed in previous versions as I have "OSM RShift" configured even though the option no longer exists

**Comment by algernon** [comment]
Hm, this is interesting... the key _is_ in the database, so something somewhere filters it out, it appears.

**Comment by algernon** [comment]
It seems that we only ever display 5 keys in that group... if I remove `Right control` from the OSM group, `Right Shift` (the next in the list) will show up. This is one funky bug.

**Comment by algernon** [comment]
HAH. Found it. When we wanted to restrict OSL keys to show only layers we have available, I typo'd the group, and we restricted the number of OSM keys to the number of available layers instead.
