### ISSUE TITLE
Model 01: JS error after installing latest firmware - white screen

### ISSUE THREAD

**Issue by thejonanshow** [keyboardio/Chrysalis#551]
**Describe the bug**
1. Install firmware
2. Connect
3. Admire JS errors in console

**Expected behavior**
None errors instead of some.

**Screenshots**
![Screen Shot 2020-08-12 at 3 55 10 PM](https://user-images.githubusercontent.com/270746/90076816-8cf0bd00-dcb5-11ea-8fa4-04c9a14cf071.png)
![Screen Shot 2020-08-12 at 4 05 09 PM](https://user-images.githubusercontent.com/270746/90076858-9e39c980-dcb5-11ea-8bb7-bc41aefe2bac.png)

**Desktop (please complete the following information):**
 - Chrysalis Version: 0.7.9+258

**Additional context**
Tried installing firmware from Chrysalis (beta) and then reinstalled with firmware from Arduino, same result.

**Comment by obra** [comment]
Hi Jonan,

Do you also get this error on Kaleidoscope 0.7.9, the latest release?

**Comment by thejonanshow** [comment]
I used the Arduino examples Model 01 firmware most recently, can I assume by your question that this is not the latest version?

**Comment by obra** [comment]
So sorry. I meant to write "Chrysalis 0.7.9" - the latest 'release' build

**Comment by algernon** [comment]
This has been fixed on master, and the fix will be available in the next release.
