### ISSUE TITLE
Gui modifier key checkbox should be localized

### ISSUE THREAD

**Issue by alfalfasprossen** [keyboardio/Chrysalis#564]
The *Gui* modifier checkbox for combining with other keys is not localized in a system-specific way. It is correctly translated on the key labels and in the *Modifiers and Locks* category. The checkbox should be localized as well to prevent confusion.

![image](https://user-images.githubusercontent.com/7073908/94969628-6277ef00-0503-11eb-8896-0fb42fa5b9c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, MacOS
 - Chrysalis Version: 0.7.9

**Comment by Rom1deTroyes** [comment]
Does the TODO here is to extract the substring "Gui" from all the place in `src/api/keymap/db/*.js` , and replace with the `guiLabel` var from `src/api/keymap/db/gui.js` (like in the OSM file) ?

Is there a plan for extracting other things (I think for internationalization : Right / Left, Enter, Escape, ...) ?

**Comment by algernon** [comment]
I wouldn't worry about this just yet - I'm rebuilding both the database and the key selector to work _very_ differently. We'll need to do the localisations (both language & platform ones) very differently.

**Comment by algernon** [comment]
This is partially fixed on master - the Gui key is localized both on the keymap, and in the sidebar. The short label is not localized yet, though. I'll see if I can fix that easily.
