### ISSUE TITLE
UI elements do not appear if the window is too small

### ISSUE THREAD

**Issue by skyfaller** [keyboardio/Chrysalis#579]
**Describe the bug**
If you select a key and the window is not large enough, you will not receive the option to "Layer shift when held, normal key otherwise". It will not be possible to scroll to see it. Only enlarging the window will make that option appear.

**To Reproduce**
1. Select a key, such as Esc
2. Shrink the width of the window until the "modifier when held, normal key otherwise" option jumps to the next line
3. Observe that the "layer shift" toggle has now vanished
4. Note that scrolling is of no avail

**Expected behavior**
Shrinking the window width and bumping the "modifier when held" toggle to the next line should not bump the "layer shift" toggle out of visibility. Instead, both options should remain visible, using scrolling if necessary, no matter what size the window is.

**Screenshots**
![Screenshot from 2020-10-08 10-02-27](https://user-images.githubusercontent.com/80093/95640158-6a86e000-0a69-11eb-8a0e-c4640b83da15.png)
![Screenshot from 2020-10-09 19-39-38](https://user-images.githubusercontent.com/80093/95640163-6d81d080-0a69-11eb-96ba-4fd596e74c98.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 LTS - AMD 64-bit, Gnome 3.36.3, using Wayland
 - Chrysalis Version: Chrysalis 0.7.9 AppImage

**Additional context**
Looks like it might happen on Windows as well? https://community.keyboard.io/t/atreus-upper-layer-via-esc-key-not-working/4178/9

**Comment by algernon** [comment]
I think that with the Editor rework in 0.8.0, this should no longer be an issue:

![Screenshot from 2021-01-25 16-28-54](https://user-images.githubusercontent.com/17243/105726519-74562580-5f2a-11eb-8490-8d1e3d2e49f5.png)
![Screenshot from 2021-01-25 16-28-46](https://user-images.githubusercontent.com/17243/105726524-74eebc00-5f2a-11eb-9bb7-95e5a0347915.png)

If it still is the case, though, please feel free to reopen!
