### ISSUE TITLE
Generate printable or exportable keymap/layout

### ISSUE THREAD

**Issue by James-Firth** [keyboardio/Chrysalis#583]
**Is your feature request related to a problem? Please describe.**
New keymaps often require lots of referencing if you're not used to the layout. Places like http://www.keyboard-layout-editor.com/ use a different format than the layer export feature.

**Describe the solution you'd like**
I would like one or both of these options:
1. Generate an image or pdf that shows selected layers. combined would be ideal (similar to how the laminated one looks from the keyboardio Atreus kickstarter)
2. Generate json that would work with something like keyboard layout editor (website linked above)

**Describe alternatives you've considered**
Manually transcribing on to the provided laminated layout. This can take a while for a big change, but is certainly a reasonable option.

**Comment by gspringtech** [comment]
I would also like a printable key layout. This _could_ be achieved using the SVG generated by the Keymap.js. I have tested by logging ReactDOMServer.renderToString(layer) in the Editor.js - but I'm not a React expert so not sure how to progress from there. The SVG would need a stylesheet added to change the text and fill colours.

**Comment by obra** [comment]
This is now available in the latest snapshot release.
