### ISSUE TITLE
Support move to layer on key up

### ISSUE THREAD

**Issue by jovannic** [keyboardio/Chrysalis#596]
I have a Keboardio Atreus

I'd like to set it up so releasing Fun after keeping it held while moving to Layer 2 resets it back to Layer 0. 

I can't figure out a way to set it up to trigger move on key up instead of or in addition to on key down.

**Comment by algernon** [comment]
I think you're looking for `Shift to Layer`, no?

`Shift to Layer` will shift to the target layer while held, but will deactivate said layer when the key is released. That seems to match your description, as far as I see.
