### ISSUE TITLE
The non-US pound sign is not available to select

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Chrysalis#606]
There doesn't appear to be a way to assign `Key_NonUsPound` to a keymap entry. I've looked through the code, and seen that `Key_NonUsBackslash` is in the "punctuation" group; the non-US pound sign (or "hash") should be there, too.

(Two people have asked about this on Discord in the past couple of days.)

**Comment by algernon** [comment]
This has been fixed in 0.8.0:

```
  {
    code: 50,
    label: {
      hint: {
        full: "Alternate",
        "1u": "Alt."
      },
      base: "#",
      shifted: "~"
    }
  },
```
