### ISSUE TITLE
Exports of system information shouldn't include localized strings

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#618]
@algernon asked me to open this bug report.

**Comment by algernon** [comment]
We no longer include localized strings. We do include a number of useless information, such as the keymap SVG in some cases. I'll keep this open, but we're looking at filtering out the useless stuff from there, rather than localized strings in particular.

**Comment by algernon** [comment]
Hmm.... it looks like we only include those SVGs in the `found_devices` log messages, that was easy to filter out. Not sure if that's the best way, but it was easy, and only a few lines. A proper solution (completely separating the device info object and the SVG component) would've taken much more effort for very, very little gain.
