### ISSUE TITLE
How to add new layers in v0.8.0?

### ISSUE THREAD

**Issue by kkga** [keyboardio/Chrysalis#629]
I feel like an idiot, because obviously I'm missing something, but where is the action to add a new layer in the latest release?

**Comment by algernon** [comment]
It's not possible (never was) to add completely new layers - only as many layers are available as much the firmware supports. However, 0.8.0 will, by default, only show layers that aren't empty. There's a "Show empty layers..." button below the mapping table on the sidebar. If you click that, it will show the empty layers too, you can click any row to switch to that layer in Chrysalis, and start mapping keys.

Does this answer your question?

**Comment by kkga** [comment]
Unfortunately, I don't see the "Show empty layers..." button. This is the full height of the sidebar (AppImage release).

![image](https://user-images.githubusercontent.com/1460122/104470852-37556f00-55cb-11eb-98b5-b6d5bff70710.png)

**Comment by algernon** [comment]
I see. That's a bug then, will fix in a bit. Thanks!

**Comment by algernon** [comment]
Found the issue, pushed a fix, travis should build a binary in about 30 minutes or so. Sorry about that, I mixed up a condition, and it was completely backwards.

**Comment by kkga** [comment]
@algernon how do I get the updated binary that includes this fix? The releases page still lists only the 0.8.0 version.

**Comment by YarmoM** [comment]
+1, hoping a new version is being released soon

**Comment by algernon** [comment]
We now have development builds again, currently available here: https://github.com/keyboardio/Chrysalis/releases/tag/v0.8.1-snapshot

The README will be updated with the new links soon.
