### ISSUE TITLE
Cannot install read/write permissions

### ISSUE THREAD

**Issue by KaeJaye** [keyboardio/Chrysalis#650]
**Describe the Bug**
Upon connecting the keyboard to laptop, a error message pops up regarding read/write permission. Clicking the "Fix Now" button results in a further error message. 

**To Reproduce**
See Above

**Expected Behavior**
The udev file to download and for the keyboard to be able to communicate with the Laptop.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also include the debug bundle you can create on the "System Information" screen. If, for some reason, you are unable to access that screen, please press `Control + Shift + I` to bring up the developer console. Right-clicking inside it will allow you to save its contents to a file - please attach that to the bug report.
<img width="1202" alt="Screen Shot 2021-02-01 at 11 17 59 pm" src="https://user-images.githubusercontent.com/78357419/106467444-c1209a00-64f0-11eb-8abb-3704817e93ca.png">

**Desktop**
 -OS: iOS 10.15.7
 - Chrysalis Version: 0.8.2

**Additional context**

**Comment by algernon** [comment]
The warning shouldn't even appear on iOS, I guess I'll need to guard its showing a bit more thoroughly.
