### ISSUE TITLE
0.8.3 - Snapshot, Layer #2 default volume keys #18665, #18666, #18637 not displayed with human readable description or graphic

### ISSUE THREAD

**Issue by tmarzolf** [keyboardio/Chrysalis#654]
**Describe the bug**
0.8.3 - Snapshot, default keys #18665, #18666, #18637 on layer #2 not displayed with human readable descriptions or graphics

**To Reproduce**
1. Using 0.8.3- Snapshot, update Atreus Firmware and restore factory defaults
2. Click on "Layer 2" in Chrysalis
4. See keys numbered #18665, #18666, and #18637

**Expected behavior**
See human readable names or graphics , not numbers ( I suspect these should be graphics for volume up, volume down and play respectively) 

**Screenshots**

![image](https://user-images.githubusercontent.com/63314904/106627629-fbb52180-6546-11eb-985e-ad62a6a73327.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chrysalis Version: 0.8.3-Snapshot

**Comment by algernon** [comment]
I suspect this is the same issue as #617, so I'm marking this as a duplicate. Fix coming up shortly!
