### ISSUE TITLE
Default layout numbering does not match the editor's numbering when there are hardcoded layers on the device

### ISSUE THREAD

**Issue by hnrklssn** [keyboardio/Chrysalis#657]
**Describe the bug**
To have layer 0 from the Chrysalis layout editor be the default I need to set layer 3 as the default. I don't mind that I can't access the hardcoded layers as I don't use them, but it's confusing that they're included in one numbering and not the other.

**To Reproduce**
1. Alter layer 0
2. Save layout
3. Go to preferences
4. Set default layer to 0
5. Save changes
6. The layer in use on the keyboard is no longer the custom layer

**Expected behavior**
I expect the numbers to match.

**Desktop:**
 - OS: Windows 10
 - Chrysalis Version: 0.8.3-snapshot

**Comment by algernon** [comment]
Chrysalis now requires that hardcoded layers not be in use, thus setting the default layer should work as one would expect.
