### ISSUE TITLE
Add json extension when saving a layout to a file

### ISSUE THREAD

**Issue by roipoussiere** [keyboardio/Chrysalis#663]
**Is your feature request related to a problem? Please describe.**

When saving the keyboard layout to a file, I would like to open it with a text editor. To enable syntax highlighting, I had to rename it and add the json extension.

**Describe the solution you'd like**

The json extension could be automatically added when saving a layout as file.

**Comment by Rom1deTroyes** [comment]
I always export to the same file, so I never fill the filename, nor the extension, but I agree on this :+1: 

I choose `Layout.json` as default name, but maybe @obra has a better option (I haven't read all the messages about disambiguation of Layout, Layers, Keymap & Co !)
