### ISSUE TITLE
Locking layer #1

### ISSUE THREAD

**Issue by snan** [keyboardio/Chrysalis#666]
Is there a way to lock layer #1?
I can lock layer #2 without problems.

This is on the Keyboardio version of Atreus using Chrysalis.

**Comment by necsoiu** [comment]
> Is there a way to lock layer #1?
> I can lock layer #2 without problems.
> 
> This is on the Keyboardio version of Atreus using Chrysalis.

https://github.com/keyboardio/Chrysalis/issues/620

**Comment by snan** [comment]
Duplicate of #620.
