### ISSUE TITLE
Unable to select layer shift when held for secondary action

### ISSUE THREAD

**Issue by kujohn** [keyboardio/Chrysalis#673]
**Describe the bug**
When selecting `layer shift when held` as secondary action, it defaults to `modifiers when held` and turns on `altGr`.

**Screenshots**
![2021-03-07 20 07 47](https://user-images.githubusercontent.com/1356936/110273347-42040300-7f81-11eb-8cb7-ff09ddbbd754.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS X 11.2.2 (20D80)
 - Chrysalis Version: 0.8.2

**Comment by Rom1deTroyes** [comment]
Can you try with the last [development snapshot](https://github.com/keyboardio/Chrysalis/releases/tag/v0.8.3-snapshot) ?
There is a lot of displaying problems that has been addressed sine 0.8.2 :smile:

**Comment by tzwilliams** [comment]
@Rom1deTroyes, I had the same problem using 0.8.2 on Windows 10 (20H2).  I just updated to the 0.8.3 development snapshot and the issue seems be corrected.  Thanks!

**Comment by Rom1deTroyes** [comment]
Chrysalis-O.8.3 release is out there, so I think this issue can be closed ?

**Comment by algernon** [comment]
Indeed, this should be closed as fixed in 0.8.3. Thanks for the reminder, and for the report too!
