### ISSUE TITLE
0.8.3 - Consumer control icons does't show anymore

### ISSUE THREAD

**Issue by necsoiu** [keyboardio/Chrysalis#680]
**Describe the bug**
Consumer control icons does't show anymore, just numbers displayed.

![Consumer control](https://user-images.githubusercontent.com/1866443/113485004-0e4ec700-94b4-11eb-8a52-437cf3572353.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrysalis Version: [e.g. 0.8.3]

**Comment by Rom1deTroyes** [comment]
Please, see #677 and #678
