### ISSUE TITLE
Download badges are missing

### ISSUE THREAD

**Issue by fvaneerden** [keyboardio/Chrysalis#686]
Small issue: under the [installation](https://github.com/keyboardio/Chrysalis#from-installer-packages) section the following is written:
```
From installer packages

Click on the badge for your operating system's packaging system above
```
The badges seemed to have disappeared though...

**Comment by algernon** [comment]
They seem to be still available in the [Downloads](https://github.com/keyboardio/Chrysalis#downloads) section, just below the screenshot at the top. Perhaps we should link to that section in the installation part, so the browser scrolls up...

**Comment by algernon** [comment]
After adding a link, I re-read the section, and it was, indeed outdated, as it referred to per-os badges, which we no longer provide, but link to the appropriate GitHub release instead. I adjusted the section accordingly.

Thank you!

**Comment by fvaneerden** [comment]
Thanks for the quick fix!
