### ISSUE TITLE
Once toggled, the Shift modifier on the left Shift key cannot be untoggled.

### ISSUE THREAD

**Issue by parke** [keyboardio/Chrysalis#705]
In Chrysalis 0.8.4, select the left Shift key.  Then toggle on the Shift modifier for that key.  They key will now be "S+ Shift" (which, admittedly, does not make a lot of sense).  However, it will now be impossible to untoggle the Shift modifier.

The only solution I have found is to reassign the key to something other than left Shift, then remove the Shift modifier, then reassign the key back to left Shift.

Perhaps it should not be possible to apply a Shift modifier to the left Shift key?

It feels really strange to be able to turn the toggle on, but not off.

The same thing seems to happen with left Control.  (Perhaps it will also happen with left Alt, left Super, and AltGr, but I have not tested those.)

**Comment by gedankenexperimenter** [comment]
While the behaviour described is certainly a UI bug, it should be quite harmless; Kaleidoscope has no problem with modifier flags on modifier keys, even if the flag duplicates the keycode.  Does it only happen when applying the `shift` modifier to the _left_ `shift` key, or does it also happen with _right_ shift?

**Comment by parke** [comment]
It appears the right Shift key is not affected.

**Comment by TrueFalcon** [comment]
Another way to reset the key is to just click the X at top left in front of "LAYOUT EDITOR" and confirm that you are OK with losing your unsaved changes.
