### ISSUE TITLE
The current layer indicator should be always visible

### ISSUE THREAD

**Issue by TrueFalcon** [keyboardio/Chrysalis#711]
When the right menu scrolls, the layer number disappears. Could we get an indicator somewhere in the main window showing the selected layer?

Possible locations are top left, right beside the current layer before it disappears, or centered under the keyboard image.

**Comment by algernon** [comment]
We could make the "Layer $N" label stay sticky at the top of the sidebar, while the rest scrolls. At least I think we can do that.

**Comment by obra** [comment]
This bit of the UI has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior
