### ISSUE TITLE
Apple Silicon/M1 build

### ISSUE THREAD

**Issue by Godatplay** [keyboardio/Chrysalis#731]
It'd be great to have a macOS build that supports Apple Silicon / M1 / aarch64 / is a Universal app.

**Comment by obra** [comment]
The default macos build should support Apple Silicon machines. I agree that
it'd be ideal to have builds *optimized* for aarch64, but my recollection
is that that is blocked on github offering M1 based runners.

-j

**Comment by algernon** [comment]
Theoretically, we can use custom runners. So if there's anyone who can offer us an M1 runner, maintain it, etc, we can make use of it, and don't have to wait for GitHub themselves to offer it.

**Comment by Godatplay** [comment]
> The default macos build should support Apple Silicon machines.
Oh! By "default" do you mean the one on brew? The 0.8.3 Github build requires Rosetta

**Comment by algernon** [comment]
While this was closed a while ago, with #764 merged, our builds should now be Universal apps, and as such, should support M1 too.
