### ISSUE TITLE
Problem assigning tap/hold modifiers

### ISSUE THREAD

**Issue by cobblepot1** [keyboardio/Chrysalis#737]
**Describe the bug**
I cannot assign `Modifier when held` to multiple keys.

**To Reproduce**
1. I'm trying to set up home row mods for my Atreus, so for key A I added Secondary Action "Modifier when held" and set it to "Alt". No problem there. 
2. But trying the same thing with any other key/modifier combination deletes the layer #0 assigned main key and replaces it with #[object Object]. I've tried different combos of modifiers and only the first change to key A works. I also see  #[object Object] on the graphical keyboard display in Chrysalis

**Expected behavior**
I expect to be able to assign e.g. key `U` to type "u" when tapped and `Ctrl` when held down.

**Screenshots**
![image](https://user-images.githubusercontent.com/65119937/152620998-1aef2e21-bae6-41f6-9e33-7d6146812ff3.png)
[chrysalis-debug.bundle.zip](https://github.com/keyboardio/Chrysalis/files/8007001/chrysalis-debug.bundle.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Chrysalis Version: 0.8.6

**Additional context**

**Comment by obra** [comment]
@algernon tells me he'll be able to dig into this tonight. I'm sorry it's
been hanging out so long.

**Comment by algernon** [comment]
Hi!

Apologies for this taking so long, I've been blessed with a whole lot of things that hindered my progress. The good news is, that I found the problem, and am working on a fix. It's a bit tricky, had a fix last night, but while that fixed this issue, it broke other cases. So I need to be a tiny bit smarter.

I'll have something ready soon!

**Comment by quickfold** [comment]
Hi, it's 2 weeks since last update, and 6 weeks since the bug was submitted. I understand that the Model 100 is taking priority. When should I expect another update? Thanks.

**Comment by lukeabbott** [comment]
Is this the reason my model 01 stops typing a key when I assign a secondary action?

**Comment by gedankenexperimenter** [comment]
> Is this the reason my model 01 stops typing a key when I assign a secondary action?

Can you be more specific about the issue you're having?

**Comment by lukeabbott** [comment]
In chrysalis, I attempted to assign a secondary action on hold to each of my home row keys. For example, on hold of 'a' register 'shift' modifier.

After assigning the secondary actions the keys stopped registering any key presses.

![image](https://user-images.githubusercontent.com/5643368/159197973-850864d1-69d8-4edc-b92c-7c3696138601.png)

**Comment by obra** [comment]
> Hi, it's 2 weeks since last update, and 6 weeks since the bug was submitted. I understand that the Model 100 is taking priority. When should I expect another update? Thanks.

I'm really sorry. @algernon has been out with a medical issue for most of that time. I don't have an ETA for when to expect a fix.

**Comment by lukeabbott** [comment]
> I believe this is a different issue: the keys stop registering because the default firmware does not have the necessary plugin enabled.

Thanks!

**Comment by quickfold** [comment]
@algernon 
> Are you using the dropdown to select the modifier, or the switches a block above? With the switches, I can reproduce something similar, though I do not get #[object Object] stuff, but random keycodes instead. That's the issue I was trying to fix up until now. But just when I was getting back to it today, I realized that the switches aren't meant to be used for this, the dropdown is. I can't repro with the dropdown:

I am using the dropdown. I think the issue is related to my use of the Dvorak layout. I see you have "English (US)" selected in the Linux layout above Secondary Action. Can you try with "Dvorak" selected? Mine is Windows layout with Dvorak selected. Thanks!

**Comment by algernon** [comment]
Interesting. The layout should not make a difference, but I tried with "United States (Dvorak)" selected, and still couldn't reproduce with the dropdown. Still on Linux though, will see if I can reproduce on Windows (don't expect to, but it might surpruise me).

**Comment by quickfold** [comment]
Hi @algernon , looking forward to your results from testing on Windows 10. I can recreate the bug on my machine and send you a video or debug information if you need.

**Comment by quickfold** [comment]
Hi @algernon, I hope you don't mind the reminder. I know you are busy with other things. The original bug report was submitted Feb 5, over 2 months ago. I look forward to hearing more so I can use my Atreus. Thanks!
