### ISSUE TITLE
Factory resetting EEPROM and leaving and reentering chrysalis results in a blank keymap

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#739]
Tested on an Atreus running both master and the `drain` fix branch.

**Comment by algernon** [comment]
I suspect we'll need to reset the keyboard a final time after restoring EEPROM, to make sure every plugin picks it up.

**Comment by algernon** [comment]
There are two places where we factory-reset the EEPROM: either during flashing, or on the Preferences screen. During flashing, we already reboot the keyboard after resetting EEPROM, so that part is covered. We need a reboot on the Preferences screen.
