### ISSUE TITLE
Editor: top/bottom margins on the sidebar boxes behave weirdly

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#794]
When the boxes are closed, there's no top or bottom margin:

![Screenshot from 2022-05-16 16-09-06](https://user-images.githubusercontent.com/17243/168612130-2e2c1b6d-4cbd-4a26-a77e-67e8a9ff7a15.png)

This makes the `Backup & Restore` button look misaligned, for one. But when the boxes open...

![Screenshot from 2022-05-16 16-09-51](https://user-images.githubusercontent.com/17243/168612416-436c534d-7d96-4a39-9ca2-d90c40e94182.png)

...the margins appear. That also results in a weird vertical shift, as the top margin appears too.

**Comment by obra** [comment]
I'd *intended* for the vertical margins to go away so that the whole thing works as more of an accordion view. But it shouldn't be causing things to jump around.

**Comment by algernon** [comment]
Agreed. The margins being gone is a good thing. But there should be a bottom margin for the backup & restore button, and the accordion view shouldn't jump around, either, not their top, at least. They should ease out towards the bottom, rather than both ways, imo.

**Comment by algernon** [comment]
The backup & restore button not having a margin is already fixed on master. Turns out we were using `<div sx={{ ... }}>` in a lot of places, and that doesn't work. It's the `<Box>` component that implements the `sx` API, so we need to use a component derived from that.

**Comment by algernon** [comment]
Fixed on `jesse-wip`, in 7d5cf8673729a8f3298d07ae8792a6549448360e. Will need to cherry-pick that to master eventually.
