### ISSUE TITLE
Save changes not working [Windows]

### ISSUE THREAD

**Issue by davidaue** [keyboardio/Chrysalis#81]
Using 0.0.6 binary installer on Windows 10.

Change a key mapping on layer 3 and save changes.
Go to info icon, back to keyboard icon, layer 3.
Old mapping is shown.
Also does not take effect in the keyboard.

**Comment by algernon** [comment]
We probably fixed this somewhere along the way. I can't reproduce this with current master, nor can a few other people who gave Chrysalis a spin on Win10.

**Comment by davidaue** [comment]
I'll check it out the next time a Windows installer is released. I'm still having trouble with the 0.1.0 release.
