### ISSUE TITLE
Add way to save default LED profile

### ISSUE THREAD

**Issue by zekesulastin** [keyboardio/Chrysalis#846]
**Is your feature request related to a problem? Please describe.**
The LED profile resets every time the keyboard is power cycled/reconnected/etc

**Describe the solution you'd like**
An option in Chrysalis to store the default profile on the keyboard would be neat (maybe even editing them down the line).  This may be out of scope, but maybe also having the board remember what you cycled it to if you change it on keyboard.  (Feature req for the eeprom plugin?)

**Describe alternatives you've considered**
Going full custom firmware eventually!

**Additional context**
Here's the reminder as requested!

**Comment by algernon** [comment]
This is fairly trivial to implement with a tiny focus plugin, which we could even include in most default firmware. Then we add a setting to "My Keyboard" in Preferences, and we're good to go.
