### ISSUE TITLE
0.9.5 on Windows punts us back to the Keyboard selection screen

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#849]
We've received multiple reports that on at least Windows 10, connecting to a Model 100 does not work. The loading screen appears, but we're getting punted back to the keyboard selection screen without any error or warning. 0.9.4 did not have this problem, so it's a regression since.

The debug bundles provided to us aren't very helpful: they show that Chrysalis connects to the keyboard, there's communication back and forth, everything seems to be in order. Then, after a couple of commands, the next one we get is the debug log from the Keyboard Select screen's periodic scan.

I suspect this may be related to #830, because we had another issue, where we _did_ get an error message, about `activeDevice` not having a `.devicePath()` method, due to `activeDevice` being null. I fixed that in af6cee129b941c75bb726a7ca9840e1e33801522, but the problem still persists.

**Comment by necdetaliozdur** [comment]
> We've received multiple reports that on at least Windows 10, connecting to a Model 100 does not work.

I just want to add that connecting to an Atreus does not work either. I'm on Windows 11. I reverted back to 0.9.4 which solved the issue.

**Comment by algernon** [comment]
Reproduced on my Win10 VM: 0.9.4 works, can connect, 0.9.5 and later punts me back to the selection screen immediately. My windows build environment is still updating, it will take a while, but I'll go and bisect Chrysalis as soon as its done.

**Comment by algernon** [comment]
Interestingly, bisecting ended up declaring aef6231c94f24cb76bd65621d6d6f41ede86aa9e as the culprit. That does not make much sense yet.

**Comment by algernon** [comment]
Progress! Checking aef6231c94f24cb76bd65621d6d6f41ede86aa9e out, and **not** updating dependencies: we can connect. As soon as I run yarn, we break. However, checking out `package.json` and `yarn.lock` from the prior commit: we still break.

This suggests that my bisecting wasn't adequate. It also suggests that what we're looking for is yarn.lock changes between 0.9.4 and 0.9.5. The problem will be somewhere there.

**Comment by algernon** [comment]
Yep. It's going to be one of the dependencies. `git checkout v0.9.4 -- package.json yarn.lock && yarn && yarn run start` on current master lets me connect.

**Comment by algernon** [comment]
Looks like we ended up upgrading `usb` from 2.3.1 to 2.4.1. It appears the bug was introduced in usb 2.4.0, and fixed in 2.4.2 released ~21 hours ago. Upgrading to 2.4.2 fixes the problem on my VM.
