### ISSUE TITLE
Ctrl-P force closes Chrysalis in Win10

### ISSUE THREAD

**Issue by rhomboid-shovel** [keyboardio/Chrysalis#861]
**Describe the bug**
Typing Ctrl-P in Chrysalis in Win10 causes a force-close

**To Reproduce**
1. Connect to keyboard
2. Type Ctrl-P (from either Layout & Colormap Editor or Layout Card)
3. This results in Chrysalis terminating

**Expected behavior**
A print dialog, or nothing.

**Debug Bundle**
[chrysalis-debug.bundle.json.zip](https://github.com/keyboardio/Chrysalis/files/8793846/chrysalis-debug.bundle.json.zip)

**Desktop (please complete the following information):**
 - OS: Win10 Home 10H2 (19044.1706)
 - Chrysalis Version: 0.9.6-snapshot.221

**Comment by algernon** [comment]
I've reproduced the problem.

Found an issue in the Electron bugtracker about printing crashing on linux with no printer present, so figured that might be the case on Windows too, but no: attaching a printer still crashes the process. So far, wading through the Electron bugtracker didn't yield any useful results.

I did manage to get a crash dump, so will try to see if I can discern anything from that.

**Comment by algernon** [comment]
Interestingly, calling `window.print()` from the developer console doesn't crash.

**Comment by algernon** [comment]
To narrow the problem down, I created a [small test case](https://github.com/algernon/electron-print-crash), to see if that works on Windows, because I don't see anything relevant in the Electron bug tracker, and I can't believe we're the only ones seeing the issue.

The test case crashes on Linux, too.

**Comment by rhomboid-shovel** [comment]
fixed for me with snapshot.266

**Comment by rhomboid-shovel** [comment]
Wow, I didn't know I had the power to close an issue. Hope I didn't screw anything up!

**Comment by algernon** [comment]
As the original reporter, you can close the issue. In this case, doing so after you verified that the fix works is perfect.

Thank you!
