### ISSUE TITLE
FR : Key picker dark theme

### ISSUE THREAD

**Issue by Rom1deTroyes** [keyboardio/Chrysalis#862]
The picker keyboard is white for the dark theme (I know, there is extremist for the question !)

**Describe the solution you'd like**
Having a dark background, to save my eyes ;-)

**Describe alternatives you've considered**
Taking the colors from the UI Theme ?

**Comment by obra** [comment]
Can you share a screenshot? I’m not seeing this

**Comment by algernon** [comment]
![Screenshot from 2022-05-30 03-48-14](https://user-images.githubusercontent.com/17243/170902780-779357c3-60be-4be9-a456-b152fb85d9e9.png)

This, indeed, doesn't look that good.

**Comment by algernon** [comment]
This has been addressed by #868, and is fixed on master.
