### ISSUE TITLE
Figure out a naming policy for IPC methods

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#876]
We don't really have a policy on naming our IPC methods, so we ended up with a bunch of different styles:

- `service.method`: Like `backup.list-library`, `backup.load-file`, etc.
- `service-method`: Like `usb-scan-for-devices`, `focus-find-serial-devices`, etc
- none of the above: `show-devtools`, `devtools-is-open`

Thankfully, we don't have many IPC methods yet, so we can switch to a common policy with little effort. We just need to figure out how we want to name things.

**Comment by algernon** [comment]
Additionally to this, we also want a policy - possibly the same one - to cover when to use `ipcMain.on` and `ipcRenderer.send`/`sendSync`, and when to use `ipcMain.handle` and `ipcRenderer.invoke`.

I already see a few places that use `sendSync` when `invoke` would be a better choice.

**Comment by algernon** [comment]
To get this rolling, I'd prefer either `service/method` or `service.method`, where `method` would be a verb, most of the time. Thus our current ipc names would become:

- `backups.list-library`, `backups.load-file`, `backups.save-file`
- `usb.scan-for-devices`, `usb.is-device-connected, `usb.find-serial-devices`
- `dialog.file-save-show`, `dialog.file-open-show`
- `devtools.set-state` (or `devtools.open` + `devtools.close`), `devtools.is-open`
- `logging.get-filename`
- `native-theme.should-use-dark-colors`

**Comment by obra** [comment]
sure
