### ISSUE TITLE
"My Keyboard" is getting crowded, again

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#880]
The "My Keyboard" tab of Preferences is getting a bit crowded, and while sections are neatly separated, some of the knobs that belong together, aren't. This isn't really a problem _yet_, because most regions only have a single setting, or settings that are stand-alone. But #879 introduces a pair of settings that are bound together, and that makes the tab a lot less clear. We also have a lot of empty screen real estate. On top of all that, the spacing between the elements isn't exactly clear or consistent.

So I've been thinking: what if we re-introduced Cards here? Every setting that belongs together, would be in a card. Or at least on an elevated Paper. Not necessarily stacked below each other, but perhaps in a Grid, or just a flex Box, or a Masonry (from MUI's Labs)?

We should group them up, one way or the other, is what I'm trying to say, really. And not waste horizontal space, either.

Time permitting, I'll post a few mockups to show what I'm thinking of.

**Comment by obra** [comment]
Grouping settings is great. I think that the most straightforward solution to the problem you're running into right now is that "LED Preferences" is too general a grouping. (As will be 'Plugin preferences') More smaller sections that live on Papers so they are better broken apart seems like a simple way to deal.

I know that Masonry would be wrong. 

I'm not convinced that wasting horizontal space is a horrible sin.  

I can't think of another desktop application that sticks settings in a grid and looks reasonable.

Just surveying things that are currently open on my Mac:

MS Edge (Material, chrome-derived)

![image](https://user-images.githubusercontent.com/45416/171252887-7b2053a2-db65-4fb7-bf84-26cee5a95a39.png)

Excel:
![image](https://user-images.githubusercontent.com/45416/171252990-4cbc1745-2e5c-4e70-8ed9-d1204e80dc8a.png)

Slack:
![image](https://user-images.githubusercontent.com/45416/171253088-ca04959b-517f-4d3b-816c-dfe8c24a9049.png)

VS Code:

![image](https://user-images.githubusercontent.com/45416/171253146-605f6384-9280-428f-be3a-3d79f624c35a.png)

Discord:
![image](https://user-images.githubusercontent.com/45416/171253246-44ba2a92-5e2f-42be-b881-bddc5a083091.png)

WeChat:
![image](https://user-images.githubusercontent.com/45416/171253330-20904c8c-afaf-42e8-8dc2-d22456a02960.png)

Safari:

![image](https://user-images.githubusercontent.com/45416/171253419-0a93c219-8f7b-490e-9a3a-4aec0970e20c.png)

Warp:
![image](https://user-images.githubusercontent.com/45416/171253539-a68267c6-25cc-4612-a57b-cc6be6d45b11.png)

**Comment by algernon** [comment]
Progress report:

![Screenshot from 2022-06-01 04-23-03](https://user-images.githubusercontent.com/17243/171315217-c5e011b0-eae3-4463-8cf7-53599ce30241.png)
![Screenshot from 2022-06-01 04-23-16](https://user-images.githubusercontent.com/17243/171315241-f18fd8bf-7500-44d8-aaef-a41c1d2ce9b2.png)
