### ISSUE TITLE
Save layout button gets stuck in pending state after successful updates

### ISSUE THREAD

**Issue by buzhidaoist** [keyboardio/Chrysalis#937]
**Describe the bug**
The circular button on the bottom left of the editor gets stuck in the pending state (green border spinning, and button press disabled) even after the layout change saves successfully (as evidenced by the keyboard being usable with the changes reflected).

This started occurring after I switched from the default to the experimental firmware.

1. Flash the experimental firmware
2. Make a layout change like a simple modification of a key e.g. add Shift modifier to the Z key
3. Press the orange save button on the bottom left of the editor
4. Immediately press the modified key and verify that keyboard is disabled while the configuration is being saved
5. After a few seconds, try again and observe that the keyboard is now usable and the modification has taken effect, but that the save button is still stuck with green spinning border
6. Make another layout modification and observe that the button continues to be stuck, instead of turning orange to enable saving the new modification

I can share a screen-grab or sequence of screenshots if desired. Debug bundle is attached.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4
 - Chrysalis Version: 0.10.0

[chrysalis-debug.bundle_shmxe.json.txt](https://github.com/keyboardio/Chrysalis/files/8872819/chrysalis-debug.bundle_shmxe.json.txt)

**Comment by algernon** [comment]
@buzhidaoist Can you try if the problem is reproducible with [Chrysalis 0.10.3](https://github.com/keyboardio/Chrysalis/releases/tag/v0.10.3)?

**Comment by buzhidaoist** [comment]
just updated to 0.10.4 and no longer experiencing the bug
