### ISSUE TITLE
Cant connec runing Chrysalis 0.10.1  Appimage on Clearlinux

### ISSUE THREAD

**Issue by isipka** [keyboardio/Chrysalis#938]
Chrysalis cannot read the keyboard on latest Clearlinux with connected Atreus . 
I have tried to fix this my granting access via security setting on system settings to no avail. I am not familiar enough with Chrysalis development to dig understand the error message. Please advise!

To Reproduce

Open Chrysalis
An Error message pops up saying my computer won't let Chrysalis talk to keyboard
Your computer won't let Chrysalis talk to your keyboard. (You do not have read/write permissions to /dev/ttyACM3.)
Chrysalis can fix this by installing a udev rules file into /etc/udev/rules.d/.
I click the fix it button.
Error: Command failed: cd "/home/z/Downloads"; "/usr/bin/pkexec" --disable-internal-agent /bin/bash -c "echo SUDOPROMPT; (mv /etc/udev/rules.d/60-kaleidoscope.rules /etc/udev/rules.d/60-kaleidoscope.rules.orig || true) && install -o root -g root /tmp/tmp-29477-QRILuPchKSv0 /etc/udev/rules.d/60-kaleidoscope.rules && rm /tmp/tmp-29477-QRILuPchKSv0 && udevadm control --reload-rules && udevadm trigger /dev/ttyACM3" mv: cannot stat '/etc/udev/rules.d/60-kaleidoscope.rules': No such file or directory install: cannot create regular file '/etc/udev/rules.d/60-kaleidoscope.rules': No such file or directory
Expected behavior
Be able to read keyboard.

**Comment by algernon** [comment]
Can you try creating the `/etc/udev/rules.d` directory, and then trying the "fix it" button again?
