### ISSUE TITLE
When there's a connection timeout on Linux, hint at ModemManager

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#956]
Under Linux, ModemManager is notorious for interfering with the communication between Chrysalis and the keyboard. The udev rules Chrysalis ships with help with that, but we only install those if we encounter a permission issue, so if the permissions are fine, the udev rules are never mentioned.

However, our users are repeatedly bitten by ModemManager. We should either try to check in advance whether MM is disabled for a particular device, and warn if it isn't, or - if running on Linux - mention the udev rules and ModemManager in the error message when communication times out.

**Comment by obra** [comment]
This is better in modern chrysalis
