### ISSUE TITLE
Dragging issues with the floating key picker

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#959]
The floating keypicker can be dragged around by clicking anywhere on it and dragging it around. While that can be convenient, it's also a hindrance when you want to select a key by clicking on it, but accidentally move the mouse at roughly the same time. In that case, instead of clicking the key, we end up dragging the key picker around instead.

Instead of the picker being draggable by clicking & dragging anywhere, I propose we add explicit dragbars, so that it can't so easily be dragged around by accident. A bar to the right of the Fx keys would be a reasonable spot, I believe.

**Comment by obra** [comment]
it's no longer draggable
