### ISSUE TITLE
Editing a keyboard layout without owning the keyboard (yet)

### ISSUE THREAD

**Issue by neuhaus** [keyboardio/Chrysalis#964]
I would like to edit the keyboard layout for my Model 100 which has not yet shipped.

I am unable to do so. Chrysalis will only let me do this after i have connected the keyboard to the computer running Chrysalis.

I used 0.10.2 on Mac.

**Comment by algernon** [comment]
This is something we wanted to do for a long time, but the current architecture of Chrysalis makes it hard to implement such an "offline mode". We're slowly inching closer, but it will be a while until we get there.

Meanwhile, #377 is the issue to track.
