### ISSUE TITLE
962 breaks device discovery on macos.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#967]
With a Model 100 connected:
![image](https://user-images.githubusercontent.com/45416/176093559-ea843b8c-3a3b-483a-8aca-3abf916781f8.png)
![image](https://user-images.githubusercontent.com/45416/176093590-8b1277c0-8bd1-4faf-b3a1-ee5907058cd2.png)

**Comment by obra** [comment]
I'm going to revert 962 temporarily

**Comment by algernon** [comment]
Ooops. Problem is us calling `ipcRenderer.sendSync("udev.isAvailable")` unconditionally. I'll revert the revert and fix that.

Sorry!
