### ISSUE TITLE
"migrate" button does not provide feedback

### ISSUE THREAD

**Issue by hakamadare** [keyboardio/Chrysalis#988]
**Describe the bug**
I'm unable to address whatever the issue is that Chrysalis is complaining about concerning legacy keys.

**To Reproduce**
1. Attach a Keyboardio Atreus
2. Launch Chrysalis 0.10.4 on macOS 12.4
3. Select Atreus, click Connect
4. Error message "We found legacy keys on the keymap that are no longer valid. To migrate to the new codes, please press the Migrate button." appears
5. Click MIGRATE
6. Error message remains, there's no visual feedback
7. Issue recurs after quitting Chrysalis and relaunching

**Expected behavior**
I expect to see some visual indication that the "MIGRATE" button does anything; I'm not sure that I successfully clicked it, it doesn't invert color, or flash, or do anything upon mouseDown or mouseUp events.

I expect to see some feedback after the key code migration process finishes, that either says "success" or "failure", and in the event of a failure, I expect to see an error message.

**Screenshots**
<img width="885" alt="Screen Shot 2022-07-08 at 1 46 33 PM" src="https://user-images.githubusercontent.com/154395/178044810-6ec227a6-72b1-4c64-bf14-c5a8caa663ef.png">
<img width="1194" alt="Screen Shot 2022-07-08 at 1 47 45 PM" src="https://user-images.githubusercontent.com/154395/178044847-75131a7f-9cf4-4e7d-b8b1-aaafa39c3f17.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Chrysalis Version: 0.10.4 (also occurred on 0.10.3 and 0.10.2)

**Additional context**
My firmware is out of date, I haven't been successful in updating it; I'm opening a separate ticket to track that issue.
[chrysalis-debug.bundle.json.zip](https://github.com/keyboardio/Chrysalis/files/9074237/chrysalis-debug.bundle.json.zip)

**Comment by algernon** [comment]
Turns out this happens because the function that is supposed to run when you click the "Migrate" button never runs, because:

```
react-dom.development.js?61bb:3832 Uncaught Error: Expected `onClick` listener to be a function, instead got a value of `object` type.
    at getListener (react-dom.development.js?61bb:3832:1)
    at accumulateSinglePhaseListeners (react-dom.development.js?61bb:8537:1)
    at extractEvents$4 (react-dom.development.js?61bb:8178:1)
    at extractEvents$5 (react-dom.development.js?61bb:8206:1)
    at dispatchEventsForPlugins (react-dom.development.js?61bb:8298:1)
    at eval (react-dom.development.js?61bb:8508:1)
    at batchedEventUpdates$1 (react-dom.development.js?61bb:22396:1)
    at batchedEventUpdates (react-dom.development.js?61bb:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js?61bb:8507:1)
    at attemptToDispatchEvent (react-dom.development.js?61bb:6005:1)
```

If it ran, the alert would disappear, and the keymap would be modified, with the save button at the bottom getting enabled too. So it turns out: there *is* feedback. If it runs. I just need to fix the code to run the appropriate function instead of erroring out.

**Comment by hakamadare** [comment]
Chrysalis 0.11.0 resolved this for me, thanks folks!
